import { notFound } from 'next/navigation';

export async function generateStaticParams() {
  return [
    { section: 'assignments' },
    { section: 'reports' },
    { section: 'payments' },
    { section: 'messages' },
    { section: 'resources' },
    { section: 'profile' },
  ];
}

import { BookOpen, Bug, CheckCircle2, Clock3, CreditCard, FileCheck2, Mail, MessageCircle, MonitorSmartphone, Plus, ShieldCheck, Smartphone, UserRound, WalletCards } from 'lucide-react';
import { demoAssignments, demoMessages, demoPayments, demoReports, demoResources } from '@/lib/uatDemoData';

const headings: Record<string, { eyebrow: string; title: string; copy: string }> = {
  assignments: { eyebrow: 'Testing work', title: 'Test Assignments', copy: 'Browse realistic sample assignments matched to a tester’s devices and experience.' },
  reports: { eyebrow: 'Evidence and review', title: 'Bug Reports', copy: 'Preview report history and the complete structure used to submit a useful bug.' },
  payments: { eyebrow: 'Rewards overview', title: 'Payments', copy: 'See how assignment fees, qualifying bug rewards and payouts can be presented.' },
  messages: { eyebrow: 'Project communication', title: 'Messages', copy: 'Keep assignment questions, review requests and payment updates in one place.' },
  resources: { eyebrow: 'Tester learning', title: 'Resources', copy: 'Clear guides help first-time testers produce useful, reproducible feedback.' },
  profile: { eyebrow: 'Tester settings', title: 'Profile & Availability', copy: 'Manage devices, preferred testing times and the information used for matching.' },
};

const statusTone: Record<string, string> = {
  Available: 'bg-emerald-100 text-emerald-700', 'In progress': 'bg-sky-100 text-sky-700', Completed: 'bg-slate-100 text-slate-600',
  'Pending review': 'bg-amber-100 text-amber-700', Approved: 'bg-emerald-100 text-emerald-700', Duplicate: 'bg-sky-100 text-sky-700', 'Needs evidence': 'bg-rose-100 text-rose-700', Paid: 'bg-sky-100 text-sky-700', Pending: 'bg-amber-100 text-amber-700',
};

export default async function UATPortalSectionPage({ params }: { params: Promise<{ section: string }> }) {
  const { section } = await params;
  const heading = headings[section];
  if (!heading) notFound();

  return (
    <>
      <div><p className="text-sm font-bold uppercase tracking-[0.2em] text-[#789265]">{heading.eyebrow}</p><h1 className="mt-2 font-serif text-4xl font-semibold tracking-tight sm:text-5xl">{heading.title}</h1><p className="mt-2 max-w-3xl text-slate-500">{heading.copy}</p></div>
      <div className="mt-8">{section === 'assignments' && <Assignments />}{section === 'reports' && <Reports />}{section === 'payments' && <Payments />}{section === 'messages' && <Messages />}{section === 'resources' && <Resources />}{section === 'profile' && <Profile />}</div>
    </>
  );
}

function Assignments() {
  return <div className="grid gap-5 xl:grid-cols-2">{demoAssignments.map(({ id, title, project, summary, device, duration, reward, deadline, difficulty, status, icon: Icon, checklist }) => <article key={id} className="rounded-2xl border border-slate-100 bg-white p-6 shadow-sm"><div className="flex items-start gap-4"><div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-sky-100"><Icon className="h-6 w-6 text-[#2878d0]" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${statusTone[status]}`}>{status}</span><span className="rounded-full bg-[#edf4e8] px-3 py-1 text-xs font-semibold text-[#617a50]">{difficulty}</span></div><h2 className="mt-3 font-serif text-2xl font-semibold">{title}</h2><p className="text-sm font-medium text-[#2878d0]">{project}</p></div><span className="text-xl font-bold text-[#617a50]">{reward}</span></div><p className="mt-5 text-sm leading-6 text-slate-600">{summary}</p><div className="mt-5 grid gap-3 rounded-xl bg-slate-50 p-4 text-sm text-slate-600 sm:grid-cols-3"><span className="flex items-center gap-2"><MonitorSmartphone className="h-4 w-4" />{device}</span><span className="flex items-center gap-2"><Clock3 className="h-4 w-4" />{duration}</span><span className="flex items-center gap-2"><FileCheck2 className="h-4 w-4" />{deadline}</span></div><div className="mt-5"><p className="text-sm font-semibold">Sample checklist</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{checklist.map((item) => <p key={item} className="flex items-start gap-2 text-sm text-slate-600"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-[#789265]" />{item}</p>)}</div></div><button type="button" disabled className="mt-6 w-full rounded-xl bg-[#2878d0] px-4 py-3 text-sm font-semibold text-white opacity-80">Preview assignment</button></article>)}</div>;
}

function Reports() {
  return <div className="grid gap-6 xl:grid-cols-[minmax(0,1.2fr)_420px]"><section className="overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-serif text-2xl font-semibold">Report history</h2><p className="mt-1 text-sm text-slate-500">Sample statuses demonstrate the review journey.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-400"><tr><th className="px-5 py-3">ID</th><th className="px-5 py-3">Issue</th><th className="px-5 py-3">Severity</th><th className="px-5 py-3">Submitted</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Reward</th></tr></thead><tbody className="divide-y divide-slate-100">{demoReports.map((report) => <tr key={report.id}><td className="px-5 py-4 font-semibold text-[#2878d0]">{report.id}</td><td className="px-5 py-4"><p className="font-medium">{report.title}</p><p className="mt-1 text-xs text-slate-500">{report.assignment}</p></td><td className="px-5 py-4">{report.severity}</td><td className="px-5 py-4 text-slate-500">{report.submitted}</td><td className="px-5 py-4"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${statusTone[report.status]}`}>{report.status}</span></td><td className="px-5 py-4 font-semibold">{report.reward}</td></tr>)}</tbody></table></div></section><section className="rounded-2xl border border-slate-100 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-full bg-sky-100"><Bug className="h-5 w-5 text-[#2878d0]" /></div><div><h2 className="font-serif text-2xl font-semibold">Submit a bug</h2><p className="text-sm text-slate-500">Frontend form preview</p></div></div><div className="mt-6 space-y-4">{['Assignment', 'Short issue title', 'Severity', 'Steps to reproduce', 'Expected result', 'Actual result', 'Browser and device', 'Screenshots or recording'].map((label, index) => <div key={label}><label className="text-sm font-semibold">{label}</label>{index === 3 || index === 4 || index === 5 ? <textarea disabled rows={3} placeholder={`Enter ${label.toLowerCase()}`} className="mt-2 w-full resize-none rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm" /> : <input disabled placeholder={`Enter ${label.toLowerCase()}`} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm" />}</div>)}</div><button type="button" disabled className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-[#2878d0] px-4 py-3 text-sm font-semibold text-white opacity-80"><Plus className="h-4 w-4" /> Submit preview report</button></section></div>;
}

function Payments() {
  return <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-3"><Summary icon={WalletCards} label="Example balance" value="£68.50" /><Summary icon={CreditCard} label="Next sample payout" value="£50.00" /><Summary icon={CheckCircle2} label="Lifetime example" value="£248.50" /></div><section className="overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-serif text-2xl font-semibold">Sample statement</h2><p className="mt-1 text-sm text-slate-500">No money movement or payment account is connected.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-400"><tr><th className="px-5 py-3">Reference</th><th className="px-5 py-3">Description</th><th className="px-5 py-3">Date</th><th className="px-5 py-3">Type</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Amount</th></tr></thead><tbody className="divide-y divide-slate-100">{demoPayments.map((payment) => <tr key={payment.id}><td className="px-5 py-4 font-semibold text-[#2878d0]">{payment.id}</td><td className="px-5 py-4 font-medium">{payment.description}</td><td className="px-5 py-4 text-slate-500">{payment.date}</td><td className="px-5 py-4">{payment.type}</td><td className="px-5 py-4"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${statusTone[payment.status]}`}>{payment.status}</span></td><td className="px-5 py-4 text-right font-bold">{payment.amount}</td></tr>)}</tbody></table></div></section><div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-900"><strong>Demo policy:</strong> assignment fees and bug rewards shown here are examples. Live rewards require an approved report, payment entitlement and verified payout method.</div></div>;
}

function Messages() {
  return <div className="grid gap-6 xl:grid-cols-[420px_minmax(0,1fr)]"><section className="overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-serif text-2xl font-semibold">Inbox</h2></div><div className="divide-y divide-slate-100">{demoMessages.map((message) => <button type="button" key={message.id} className={`block w-full p-5 text-left ${message.unread ? 'bg-sky-50/60' : 'bg-white'}`}><div className="flex items-center justify-between gap-3"><span className="font-semibold">{message.sender}</span><span className="text-xs text-slate-400">{message.time}</span></div><p className="mt-1 text-sm font-medium">{message.subject}</p><p className="mt-2 line-clamp-2 text-xs leading-5 text-slate-500">{message.preview}</p></button>)}</div></section><section className="rounded-2xl border border-slate-100 bg-white p-7 shadow-sm"><div className="flex h-full min-h-[420px] flex-col items-center justify-center text-center"><div className="flex h-20 w-20 items-center justify-center rounded-full bg-sky-100"><Mail className="h-9 w-9 text-[#2878d0]" /></div><h2 className="mt-5 font-serif text-3xl font-semibold">Project communication preview</h2><p className="mt-3 max-w-xl text-sm leading-6 text-slate-500">Selecting a live message would open its thread, assignment context and reply box. This demo deliberately does not send messages.</p><button type="button" disabled className="mt-6 flex items-center gap-2 rounded-xl bg-slate-100 px-5 py-3 text-sm font-semibold text-slate-500"><MessageCircle className="h-4 w-4" /> Replies unavailable in preview</button></div></section></div>;
}

function Resources() {
  return <div className="grid gap-5 md:grid-cols-2">{demoResources.map(({ title, description, icon: Icon, readingTime }) => <article key={title} className="rounded-2xl border border-slate-100 bg-white p-6 shadow-sm"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-[#edf4e8]"><Icon className="h-6 w-6 text-[#617a50]" /></div><h2 className="mt-5 font-serif text-2xl font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{description}</p><div className="mt-5 flex items-center justify-between"><span className="flex items-center gap-2 text-xs text-slate-400"><BookOpen className="h-4 w-4" />{readingTime}</span><button type="button" disabled className="text-sm font-semibold text-[#2878d0]">Open preview</button></div></article>)}</div>;
}

function Profile() {
  return <div className="grid gap-6 xl:grid-cols-[340px_minmax(0,1fr)]"><aside className="rounded-2xl border border-slate-100 bg-white p-6 text-center shadow-sm"><div className="mx-auto flex h-24 w-24 items-center justify-center rounded-full bg-[#e8f0e1] text-2xl font-bold text-[#617a50]">ST</div><h2 className="mt-4 font-serif text-2xl font-semibold">Sample Tester</h2><p className="text-sm text-slate-500">Preview account</p><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-50 p-3"><p className="text-2xl font-bold">92</p><p className="text-xs text-slate-500">Tester score</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-2xl font-bold">7</p><p className="text-xs text-slate-500">Approved bugs</p></div></div><p className="mt-5 flex items-center justify-center gap-2 text-sm text-[#617a50]"><ShieldCheck className="h-4 w-4" />Sample onboarding complete</p></aside><div className="space-y-6"><ProfileSection title="Personal details" icon={UserRound} fields={['Full name', 'Email address', 'Telephone number', 'Postcode area']} /><ProfileSection title="Devices and browsers" icon={MonitorSmartphone} fields={['Windows desktop', 'Android phone', 'Chrome browser', 'Microsoft Edge browser']} /><ProfileSection title="Availability" icon={Clock3} fields={['Weekday evenings', 'Saturday mornings', 'Up to 4 hours per week', 'Remote assignments only']} /><section className="rounded-2xl border border-slate-100 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><Smartphone className="h-5 w-5 text-[#2878d0]" /><h2 className="font-serif text-2xl font-semibold">Matching preferences</h2></div><div className="mt-5 flex flex-wrap gap-2">{['Websites', 'Mobile apps', 'Forms', 'Checkout journeys', 'Accessibility basics', 'Beginner-friendly tests'].map((item) => <span key={item} className="rounded-full bg-sky-50 px-4 py-2 text-sm font-medium text-[#2878d0]">{item}</span>)}</div><button type="button" disabled className="mt-6 rounded-xl bg-slate-100 px-5 py-3 text-sm font-semibold text-slate-500">Save unavailable in preview</button></section></div></div>;
}

function Summary({ icon: Icon, label, value }: { icon: typeof WalletCards; label: string; value: string }) { return <article className="rounded-2xl border border-slate-100 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></div><div className="flex h-12 w-12 items-center justify-center rounded-full bg-[#edf4e8]"><Icon className="h-5 w-5 text-[#617a50]" /></div></div></article>; }
function ProfileSection({ title, icon: Icon, fields }: { title: string; icon: typeof UserRound; fields: string[] }) { return <section className="rounded-2xl border border-slate-100 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><Icon className="h-5 w-5 text-[#2878d0]" /><h2 className="font-serif text-2xl font-semibold">{title}</h2></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{fields.map((field) => <div key={field} className="rounded-xl border border-slate-200 bg-slate-50 px-4 py-3"><p className="text-xs uppercase tracking-wide text-slate-400">Sample</p><p className="mt-1 text-sm font-medium">{field}</p></div>)}</div></section>; }
