export type EntityField = {
  name: string;
  note?: string;
};

export type Entity = {
  index: number;
  key: string;
  name: string;
  purpose: string;
  fields: EntityField[];
  states?: string[];
  groups?: string[];
  note?: string;
  group: string;
};

export const dataModelPrinciples = [
  'Customer isolation',
  'Engagement isolation',
  'Least privilege',
  'Immutable audit events where practical',
  'Evidence traceability',
  'Human approval gates',
  'Explicit scope enforcement',
  'Clear lifecycle states',
  'No cross-customer RAG context',
  'Minimal storage of secrets',
];

export const phases = [
  { id: 'foundation', label: 'Phase 1', title: 'Engagements, organisations & assets' },
  { id: 'scoping', label: 'Phase 2', title: 'Scope & approvals' },
  { id: 'execution', label: 'Phase 3', title: 'Runs, agents, tasks & scope validation' },
  { id: 'findings', label: 'Phase 4', title: 'Findings & evidence' },
  { id: 'remediation', label: 'Phase 5', title: 'Attack paths & remediation' },
  { id: 'reporting', label: 'Phase 6', title: 'Retests & reports' },
  { id: 'watch', label: 'Phase 7', title: 'Security Watch' },
  { id: 'audit', label: 'Phase 8', title: 'Audit hardening & retention' },
];

export const groupMeta: Record<string, { label: string; phase: string }> = {
  foundation: { label: 'Foundation', phase: 'Phase 1' },
  scoping: { label: 'Scoping & approval', phase: 'Phase 2' },
  execution: { label: 'Execution', phase: 'Phase 3' },
  findings: { label: 'Findings & evidence', phase: 'Phase 4 & 5' },
  remediation: { label: 'Remediation & reporting', phase: 'Phase 6' },
  monitoring: { label: 'Monitoring & audit', phase: 'Phase 7 & 8' },
};

export const entities: Entity[] = [
  {
    index: 1,
    key: 'organisations',
    name: 'Organisations',
    group: 'foundation',
    purpose: 'Represents the customer organisation. The root of tenant isolation.',
    fields: [
      { name: 'id' },
      { name: 'name' },
      { name: 'slug' },
      { name: 'status' },
      { name: 'primary_contact_user_id' },
      { name: 'billing_reference', note: 'Optional, reserved for later' },
      { name: 'created_at' },
      { name: 'updated_at' },
    ],
  },
  {
    index: 2,
    key: 'security_engagements',
    name: 'Security Engagements',
    group: 'foundation',
    purpose: 'Top-level security-assessment record and the anchor for everything scoped, tested and reported.',
    fields: [
      { name: 'id' },
      { name: 'organisation_id' },
      { name: 'engagement_reference' },
      { name: 'title' },
      { name: 'service_type' },
      { name: 'status' },
      { name: 'assessment_type' },
      { name: 'environment_type' },
      { name: 'requested_start_date' },
      { name: 'approved_start_at' },
      { name: 'approved_end_at' },
      { name: 'owner_user_id' },
      { name: 'primary_customer_contact_id' },
      { name: 'emergency_contact_id' },
      { name: 'scope_version' },
      { name: 'risk_summary' },
      { name: 'created_at' },
      { name: 'updated_at' },
      { name: 'completed_at' },
    ],
    states: [
      'enquiry',
      'scoping',
      'awaiting_authorisation',
      'approved',
      'scheduled',
      'active',
      'paused',
      'reporting',
      'remediation',
      'retest',
      'completed',
      'cancelled',
    ],
    note: 'Service types: ai_security_scan, ai_security_assessment, security_watch, retest. Avoid overloading one status field — separate state columns may be clearer.',
  },
  {
    index: 3,
    key: 'engagement_assets',
    name: 'Engagement Assets',
    group: 'foundation',
    purpose: 'Assets explicitly associated with an engagement. Membership does not imply permission to test.',
    fields: [
      { name: 'id' },
      { name: 'engagement_id' },
      { name: 'organisation_id' },
      { name: 'asset_type' },
      { name: 'display_name' },
      { name: 'hostname' },
      { name: 'domain' },
      { name: 'ip_address', note: 'If applicable' },
      { name: 'cloud_resource_reference' },
      { name: 'environment' },
      { name: 'ownership_verified' },
      { name: 'scope_status' },
      { name: 'notes' },
      { name: 'created_at' },
      { name: 'updated_at' },
    ],
    states: [
      'domain',
      'subdomain',
      'website',
      'application',
      'api',
      'server',
      'cloud_resource',
      'database',
      'email_domain',
      'identity_platform',
      'network',
      'ai_system',
      'other',
    ],
    note: 'Asset types do not all need every field.',
  },
  {
    index: 4,
    key: 'engagement_scope',
    name: 'Engagement Scope',
    group: 'scoping',
    purpose: 'Defines the approved Rules of Engagement. Versioned rather than mutated in place.',
    fields: [
      { name: 'id' },
      { name: 'engagement_id' },
      { name: 'organisation_id' },
      { name: 'version' },
      { name: 'status' },
      { name: 'valid_from' },
      { name: 'valid_until' },
      { name: 'testing_window' },
      { name: 'default_rate_limit' },
      { name: 'intrusive_testing_allowed' },
      { name: 'social_engineering_allowed' },
      { name: 'account_lockout_testing_allowed' },
      { name: 'destructive_testing_allowed' },
      { name: 'production_testing_allowed' },
      { name: 'emergency_stop_state' },
      { name: 'approved_by_customer' },
      { name: 'approved_by_dfp' },
      { name: 'customer_approved_at' },
      { name: 'dfp_approved_at' },
      { name: 'created_at' },
    ],
    note: 'Default risky permissions are false. A new scope version is created for changes, preserving history.',
  },
  {
    index: 5,
    key: 'scope_assets',
    name: 'Scope Assets',
    group: 'scoping',
    purpose: 'Explicitly defines what is allowed or excluded for a given scope version.',
    fields: [
      { name: 'id' },
      { name: 'scope_id' },
      { name: 'asset_id' },
      { name: 'permission_state' },
      { name: 'test_categories_allowed' },
      { name: 'rate_limit_override' },
      { name: 'restrictions' },
      { name: 'notes' },
    ],
    states: ['allowed', 'excluded', 'discovery_only', 'review_only', 'active_testing_allowed'],
    note: 'The system must never infer active-testing permission solely because an asset belongs to the organisation.',
  },
  {
    index: 6,
    key: 'approval_requests',
    name: 'Approval Requests',
    group: 'scoping',
    purpose: 'Human approval gates. Every consequential action routes through a recorded decision.',
    fields: [
      { name: 'id' },
      { name: 'organisation_id' },
      { name: 'engagement_id' },
      { name: 'run_id' },
      { name: 'finding_id', note: 'If relevant' },
      { name: 'approval_type' },
      { name: 'requested_by' },
      { name: 'requested_at' },
      { name: 'status' },
      { name: 'approved_by' },
      { name: 'approved_at' },
      { name: 'rejected_by' },
      { name: 'rejected_at' },
      { name: 'reason' },
      { name: 'expires_at' },
    ],
    states: ['pending', 'approved', 'rejected', 'expired', 'cancelled'],
    note: 'Types: scope_approval, active_testing, elevated_testing, critical_finding_confirmation, customer_escalation, remediation_retest, risk_acceptance, engagement_resume.',
  },
  {
    index: 7,
    key: 'assessment_runs',
    name: 'Assessment Runs',
    group: 'execution',
    purpose: 'One execution cycle within an engagement: discovery, full assessment, targeted follow-up, retest or monitoring.',
    fields: [
      { name: 'id' },
      { name: 'organisation_id' },
      { name: 'engagement_id' },
      { name: 'scope_id' },
      { name: 'run_type' },
      { name: 'status' },
      { name: 'started_at' },
      { name: 'completed_at' },
      { name: 'requested_by' },
      { name: 'approved_by' },
      { name: 'orchestrator_reference' },
      { name: 'execution_environment' },
      { name: 'stop_requested_at' },
      { name: 'stopped_at' },
      { name: 'stop_reason' },
    ],
    states: ['queued', 'awaiting_approval', 'running', 'pausing', 'paused', 'completed', 'failed', 'cancelled'],
  },
  {
    index: 8,
    key: 'security_agents',
    name: 'Security Agents',
    group: 'execution',
    purpose: 'Registry of logical security agents and their boundaries. No secret credentials stored here.',
    fields: [
      { name: 'id' },
      { name: 'agent_key' },
      { name: 'name' },
      { name: 'agent_type' },
      { name: 'description' },
      { name: 'execution_environment' },
      { name: 'capabilities' },
      { name: 'risk_level' },
      { name: 'requires_human_gate' },
      { name: 'enabled' },
      { name: 'created_at' },
      { name: 'updated_at' },
    ],
    states: [
      'security_master',
      'recon',
      'web_security',
      'cloud_security',
      'identity',
      'email_security',
      'vulnerability_intelligence',
      'ai_llm_security',
      'evidence',
      'risk_correlation',
      'remediation',
      'report',
    ],
  },
  {
    index: 9,
    key: 'agent_tasks',
    name: 'Agent Tasks',
    group: 'execution',
    purpose: 'Individual authorised tasks assigned to agents. Retains references back to organisation, engagement, run, approved scope and agent.',
    fields: [
      { name: 'id' },
      { name: 'organisation_id' },
      { name: 'engagement_id' },
      { name: 'run_id' },
      { name: 'scope_id' },
      { name: 'agent_id' },
      { name: 'task_type' },
      { name: 'target_asset_id' },
      { name: 'status' },
      { name: 'risk_class' },
      { name: 'approval_id' },
      { name: 'requested_at' },
      { name: 'started_at' },
      { name: 'completed_at' },
      { name: 'result_summary' },
      { name: 'error_summary' },
    ],
    note: 'Full lineage on each task provides auditability even if orchestrator state diverges.',
  },
  {
    index: 10,
    key: 'scope_validation_events',
    name: 'Scope Validation Events',
    group: 'execution',
    purpose: 'Records scope checks made before task execution — proving that out-of-scope requests were rejected.',
    fields: [
      { name: 'id' },
      { name: 'organisation_id' },
      { name: 'engagement_id' },
      { name: 'run_id' },
      { name: 'task_id' },
      { name: 'scope_id' },
      { name: 'target' },
      { name: 'requested_action' },
      { name: 'decision' },
      { name: 'reason' },
      { name: 'evaluated_at' },
    ],
    states: ['allowed', 'blocked', 'approval_required'],
  },
  {
    index: 11,
    key: 'findings',
    name: 'Findings',
    group: 'findings',
    purpose: 'Canonical validated or candidate security findings. An AI agent alone cannot mark a critical finding resolved.',
    fields: [
      { name: 'id' },
      { name: 'organisation_id' },
      { name: 'engagement_id' },
      { name: 'run_id' },
      { name: 'finding_reference' },
      { name: 'title' },
      { name: 'description' },
      { name: 'affected_asset_id' },
      { name: 'category' },
      { name: 'severity' },
      { name: 'confidence' },
      { name: 'status' },
      { name: 'discovered_by_agent_id' },
      { name: 'discovered_at' },
      { name: 'validation_state' },
      { name: 'validated_by' },
      { name: 'validated_at' },
      { name: 'business_impact' },
      { name: 'technical_impact' },
      { name: 'remediation_summary' },
      { name: 'customer_visible' },
      { name: 'created_at' },
      { name: 'updated_at' },
    ],
    states: [
      'critical',
      'high',
      'medium',
      'low',
      'informational',
    ],
    note: 'Severity values shown. Status values: discovered, needs_validation, validated, reported, remediation_in_progress, ready_for_retest, resolved, accepted_risk, false_positive.',
  },
  {
    index: 12,
    key: 'finding_evidence',
    name: 'Finding Evidence',
    group: 'findings',
    purpose: 'Stores references to supporting evidence. Redacted previews preferred; secrets not stored unnecessarily.',
    fields: [
      { name: 'id' },
      { name: 'organisation_id' },
      { name: 'engagement_id' },
      { name: 'finding_id' },
      { name: 'run_id' },
      { name: 'source_agent_id' },
      { name: 'evidence_type' },
      { name: 'storage_reference' },
      { name: 'redacted_preview' },
      { name: 'content_hash' },
      { name: 'collected_at' },
      { name: 'sensitivity' },
      { name: 'retention_class' },
      { name: 'created_at' },
    ],
    states: [
      'configuration',
      'response_metadata',
      'screenshot',
      'log_excerpt',
      'scan_result',
      'policy_state',
      'identity_state',
      'cloud_configuration',
      'manual_validation_note',
    ],
  },
  {
    index: 13,
    key: 'attack_paths',
    name: 'Attack Paths',
    group: 'findings',
    purpose: 'Groups validated findings into meaningful compromise paths.',
    fields: [
      { name: 'id' },
      { name: 'organisation_id' },
      { name: 'engagement_id' },
      { name: 'title' },
      { name: 'description' },
      { name: 'severity' },
      { name: 'business_impact' },
      { name: 'likelihood_context' },
      { name: 'status' },
      { name: 'created_by' },
      { name: 'human_validated' },
      { name: 'validated_by' },
      { name: 'created_at' },
      { name: 'updated_at' },
    ],
    states: ['candidate', 'validated', 'reported', 'mitigated', 'accepted'],
  },
  {
    index: 14,
    key: 'attack_path_nodes',
    name: 'Attack Path Nodes',
    group: 'findings',
    purpose: 'Defines ordered nodes within an attack path. Ordering is explicit.',
    fields: [
      { name: 'id' },
      { name: 'attack_path_id' },
      { name: 'sequence' },
      { name: 'finding_id' },
      { name: 'asset_id' },
      { name: 'node_type' },
      { name: 'title' },
      { name: 'description' },
    ],
  },
  {
    index: 15,
    key: 'remediation_actions',
    name: 'Remediation Actions',
    group: 'remediation',
    purpose: 'Turns findings into actionable work with an owner and verification requirement.',
    fields: [
      { name: 'id' },
      { name: 'organisation_id' },
      { name: 'engagement_id' },
      { name: 'finding_id' },
      { name: 'attack_path_id', note: 'If applicable' },
      { name: 'title' },
      { name: 'description' },
      { name: 'priority' },
      { name: 'status' },
      { name: 'owner_type' },
      { name: 'owner_reference' },
      { name: 'target_date' },
      { name: 'effort' },
      { name: 'verification_required' },
      { name: 'created_at' },
      { name: 'updated_at' },
      { name: 'completed_at' },
    ],
    states: ['proposed', 'accepted', 'in_progress', 'ready_for_verification', 'completed', 'deferred', 'accepted_risk'],
  },
  {
    index: 16,
    key: 'retest_records',
    name: 'Retest Records',
    group: 'remediation',
    purpose: 'Stores remediation verification results. unable_to_verify is never auto-converted to resolved.',
    fields: [
      { name: 'id' },
      { name: 'organisation_id' },
      { name: 'engagement_id' },
      { name: 'finding_id' },
      { name: 'remediation_action_id' },
      { name: 'run_id' },
      { name: 'scope_id' },
      { name: 'requested_at' },
      { name: 'approved_at' },
      { name: 'tested_at' },
      { name: 'initial_severity' },
      { name: 'outcome' },
      { name: 'notes' },
      { name: 'validator' },
      { name: 'evidence_reference' },
      { name: 'created_at' },
    ],
    states: ['resolved', 'partially_resolved', 'still_present', 'unable_to_verify'],
  },
  {
    index: 17,
    key: 'security_reports',
    name: 'Security Reports',
    group: 'remediation',
    purpose: 'Tracks report versions so deliverables are versioned and reviewable.',
    fields: [
      { name: 'id' },
      { name: 'organisation_id' },
      { name: 'engagement_id' },
      { name: 'report_type' },
      { name: 'version' },
      { name: 'status' },
      { name: 'generated_at' },
      { name: 'reviewed_by' },
      { name: 'approved_at' },
      { name: 'storage_reference' },
      { name: 'customer_visible' },
    ],
    states: ['draft', 'human_review', 'approved', 'published', 'superseded'],
    note: 'Report types: executive, technical, combined, retest, security_watch.',
  },
  {
    index: 18,
    key: 'report_findings',
    name: 'Report Findings',
    group: 'remediation',
    purpose: 'Explicit mapping between report versions and findings, protecting historical report integrity.',
    fields: [
      { name: 'report_id' },
      { name: 'finding_id' },
      { name: 'finding_snapshot' },
      { name: 'included_at' },
    ],
    note: 'An immutable finding snapshot is preferred over a live reference so published reports do not silently change.',
  },
  {
    index: 19,
    key: 'security_watch_configs',
    name: 'Security Watch Configs',
    group: 'monitoring',
    purpose: 'Defines authorised ongoing monitoring attached to the organisation and/or engagement baseline.',
    fields: [
      { name: 'id' },
      { name: 'organisation_id' },
      { name: 'baseline_engagement_id' },
      { name: 'status' },
      { name: 'scope_id' },
      { name: 'monitoring_categories' },
      { name: 'cadence' },
      { name: 'alert_threshold' },
      { name: 'customer_contacts' },
      { name: 'active_from' },
      { name: 'active_until' },
      { name: 'created_at' },
      { name: 'updated_at' },
    ],
    states: ['draft', 'awaiting_approval', 'active', 'paused', 'ended'],
  },
  {
    index: 20,
    key: 'security_watch_events',
    name: 'Security Watch Events',
    group: 'monitoring',
    purpose: 'Stores detected monitoring changes and their human review state.',
    fields: [
      { name: 'id' },
      { name: 'organisation_id' },
      { name: 'watch_config_id' },
      { name: 'asset_id' },
      { name: 'event_type' },
      { name: 'severity' },
      { name: 'summary' },
      { name: 'detected_at' },
      { name: 'previous_state_reference' },
      { name: 'current_state_reference' },
      { name: 'material_change' },
      { name: 'human_review_state' },
      { name: 'finding_id', note: 'If escalated' },
      { name: 'status' },
    ],
    states: [
      'new_asset',
      'new_service',
      'dns_change',
      'tls_change',
      'vulnerability_change',
      'credential_exposure_signal',
      'control_regression',
    ],
  },
  {
    index: 21,
    key: 'engagement_audit_events',
    name: 'Engagement Audit Events',
    group: 'monitoring',
    purpose: 'Immutable-style audit timeline. Never the sole source of current state — it is audit history.',
    fields: [
      { name: 'id' },
      { name: 'organisation_id' },
      { name: 'engagement_id' },
      { name: 'actor_type' },
      { name: 'actor_reference' },
      { name: 'event_type' },
      { name: 'entity_type' },
      { name: 'entity_id' },
      { name: 'metadata' },
      { name: 'occurred_at' },
    ],
    states: ['user', 'customer', 'agent', 'system', 'orchestrator'],
    note: 'Examples: scope_created, scope_approved, task_blocked, run_started, emergency_stop_requested, finding_validated, critical_finding_escalated, risk_accepted, report_published.',
  },
  {
    index: 22,
    key: 'emergency_stop_state',
    name: 'Emergency Stop State',
    group: 'monitoring',
    purpose: 'A dedicated control that supports engagement-level and run-level stop, plus an explicit authorised resume.',
    fields: [
      { name: 'id' },
      { name: 'organisation_id' },
      { name: 'engagement_id' },
      { name: 'run_id', note: 'Null for engagement-level stops' },
      { name: 'scope', note: 'engagement or run' },
      { name: 'requested_by' },
      { name: 'requested_at' },
      { name: 'reason' },
      { name: 'acknowledged_at' },
      { name: 'resumed_by' },
      { name: 'resumed_at' },
    ],
    states: ['engagement_level', 'run_level'],
    note: 'Recommended as a dedicated control table rather than a single boolean, so engagement and run stops are tracked independently with full history.',
  },
];

export const engagementStateFlow = [
  'Enquiry',
  'Scoping',
  'Awaiting Authorisation',
  'Approved',
  'Active',
  'Reporting',
  'Remediation',
  'Retest',
  'Completed',
];

export const engagementSideStates = ['Paused', 'Cancelled'];

export const findingStateFlow = [
  'Discovered',
  'Needs Validation',
  'Validated',
  'Reported',
  'Remediation',
  'Ready for Retest',
  'Resolved',
];

export const findingAltEnds = ['False Positive', 'Accepted Risk'];

export const approvalStateFlow = {
  main: ['Pending', 'Approved'],
  alternatives: ['Pending → Rejected', 'Pending → Expired'],
};

export const isolationRoles = [
  {
    role: 'Customer users',
    icon: 'ri-user-3-line',
    rules: ['See only their own organisation', 'See only customer-visible findings and reports', 'Cannot see internal DFP analysis'],
  },
  {
    role: 'DFP staff',
    icon: 'ri-shield-user-line',
    rules: ['Access according to assigned role and engagement', 'Scoped to engagements they are assigned to'],
  },
  {
    role: 'Agents',
    icon: 'ri-robot-2-line',
    rules: ['Service identity access only to explicitly required records', 'No broad customer-table browsing', 'Scoped to a specific engagement/run wherever practical'],
  },
];

export type RlsLevel = 'full' | 'own' | 'assigned' | 'visible' | 'service' | 'reference' | 'none';

export const rlsAccessLevels: {
  id: RlsLevel;
  abbr: string;
  label: string;
  desc: string;
  tone: string;
}[] = [
  { id: 'full', abbr: 'FULL', label: 'Full control plane', desc: 'DFP internal read/write within the command plane.', tone: 'bg-slate-900 text-white border-slate-900' },
  { id: 'own', abbr: 'OWN', label: 'Own organisation only', desc: 'Restricted to the customer\u2019s own organisation.', tone: 'bg-blue-50 text-blue-700 border-blue-200' },
  { id: 'assigned', abbr: 'ASGN', label: 'Assigned engagements', desc: 'Only engagements the staff member is assigned to.', tone: 'bg-indigo-50 text-indigo-700 border-indigo-200' },
  { id: 'visible', abbr: 'VIS', label: 'Customer-visible only', desc: 'Only records flagged customer_visible or published.', tone: 'bg-emerald-50 text-emerald-700 border-emerald-200' },
  { id: 'service', abbr: 'SVC', label: 'Scoped service identity', desc: 'Append/read for one engagement or run. No browsing.', tone: 'bg-amber-50 text-amber-700 border-amber-200' },
  { id: 'reference', abbr: 'REF', label: 'Read-only reference', desc: 'Reference data only. No write authority.', tone: 'bg-slate-100 text-slate-600 border-slate-200' },
  { id: 'none', abbr: 'NONE', label: 'No direct access', desc: 'Not exposed to this actor type.', tone: 'bg-slate-50 text-slate-400 border-slate-200' },
];

export type RlsPermission = 'read' | 'write' | 'approve';

export const rlsPermissionMeta: {
  id: RlsPermission;
  abbr: string;
  label: string;
  desc: string;
  tone: string;
}[] = [
  { id: 'read', abbr: 'R', label: 'Read', desc: 'Can reach and view matching records.', tone: 'bg-slate-100 text-slate-600 border-slate-200' },
  { id: 'write', abbr: 'W', label: 'Write', desc: 'Can create or update records.', tone: 'bg-sky-50 text-sky-700 border-sky-200' },
  { id: 'approve', abbr: 'A', label: 'Approve', desc: 'Can authorise, validate or sign off.', tone: 'bg-rose-50 text-rose-700 border-rose-200' },
];

export type RlsCell = { level: RlsLevel; perms: RlsPermission[] };

export const rlsMatrix: {
  entity: string;
  customer: RlsCell;
  staff: RlsCell;
  agent: RlsCell;
  note?: string;
}[] = [
  { entity: 'organisations', customer: { level: 'own', perms: ['read'] }, staff: { level: 'assigned', perms: ['read', 'write', 'approve'] }, agent: { level: 'service', perms: ['read'] }, note: 'Agents read only the organisation tied to their scope.' },
  { entity: 'security_engagements', customer: { level: 'own', perms: ['read'] }, staff: { level: 'assigned', perms: ['read', 'write', 'approve'] }, agent: { level: 'service', perms: ['read'] } },
  { entity: 'engagement_assets', customer: { level: 'own', perms: ['read'] }, staff: { level: 'assigned', perms: ['read', 'write'] }, agent: { level: 'service', perms: ['read'] } },
  { entity: 'engagement_scope', customer: { level: 'own', perms: ['read', 'approve'] }, staff: { level: 'assigned', perms: ['read', 'write'] }, agent: { level: 'service', perms: ['read'] }, note: 'Agents read scope; they never author or approve it.' },
  { entity: 'scope_assets', customer: { level: 'own', perms: ['read'] }, staff: { level: 'assigned', perms: ['read', 'write'] }, agent: { level: 'service', perms: ['read'] }, note: 'Write authority stays with DFP staff.' },
  { entity: 'approval_requests', customer: { level: 'own', perms: ['read', 'approve'] }, staff: { level: 'assigned', perms: ['read', 'write', 'approve'] }, agent: { level: 'reference', perms: ['read'] }, note: 'Agents may read gate status, never decide.' },
  { entity: 'assessment_runs', customer: { level: 'own', perms: ['read'] }, staff: { level: 'assigned', perms: ['read', 'write'] }, agent: { level: 'service', perms: ['read', 'write'] } },
  { entity: 'security_agents', customer: { level: 'none', perms: [] }, staff: { level: 'full', perms: ['read', 'write', 'approve'] }, agent: { level: 'reference', perms: ['read'] } },
  { entity: 'agent_tasks', customer: { level: 'none', perms: [] }, staff: { level: 'assigned', perms: ['read', 'write'] }, agent: { level: 'service', perms: ['read', 'write'] } },
  { entity: 'scope_validation_events', customer: { level: 'own', perms: ['read'] }, staff: { level: 'assigned', perms: ['read'] }, agent: { level: 'service', perms: ['read', 'write'] }, note: 'Agent writes are append-only decisions.' },
  { entity: 'findings', customer: { level: 'visible', perms: ['read'] }, staff: { level: 'assigned', perms: ['read', 'write', 'approve'] }, agent: { level: 'service', perms: ['read', 'write'] }, note: 'Customer sees only validated, customer-visible findings.' },
  { entity: 'finding_evidence', customer: { level: 'visible', perms: ['read'] }, staff: { level: 'assigned', perms: ['read', 'write'] }, agent: { level: 'service', perms: ['read', 'write'] }, note: 'Customer sees redacted previews only.' },
  { entity: 'attack_paths', customer: { level: 'visible', perms: ['read'] }, staff: { level: 'assigned', perms: ['read', 'write', 'approve'] }, agent: { level: 'service', perms: ['read', 'write'] } },
  { entity: 'attack_path_nodes', customer: { level: 'visible', perms: ['read'] }, staff: { level: 'assigned', perms: ['read', 'write'] }, agent: { level: 'service', perms: ['read', 'write'] } },
  { entity: 'remediation_actions', customer: { level: 'own', perms: ['read', 'write'] }, staff: { level: 'assigned', perms: ['read', 'write', 'approve'] }, agent: { level: 'service', perms: ['read', 'write'] }, note: 'Customer may update action status on their own items.' },
  { entity: 'retest_records', customer: { level: 'visible', perms: ['read'] }, staff: { level: 'assigned', perms: ['read', 'write', 'approve'] }, agent: { level: 'service', perms: ['read', 'write'] } },
  { entity: 'security_reports', customer: { level: 'visible', perms: ['read'] }, staff: { level: 'assigned', perms: ['read', 'write', 'approve'] }, agent: { level: 'service', perms: ['read', 'write'] }, note: 'Customer sees published reports only.' },
  { entity: 'report_findings', customer: { level: 'visible', perms: ['read'] }, staff: { level: 'assigned', perms: ['read', 'write'] }, agent: { level: 'service', perms: ['read', 'write'] } },
  { entity: 'security_watch_configs', customer: { level: 'own', perms: ['read', 'approve'] }, staff: { level: 'assigned', perms: ['read', 'write', 'approve'] }, agent: { level: 'service', perms: ['read'] } },
  { entity: 'security_watch_events', customer: { level: 'visible', perms: ['read'] }, staff: { level: 'assigned', perms: ['read', 'write'] }, agent: { level: 'service', perms: ['read', 'write'] } },
  { entity: 'engagement_audit_events', customer: { level: 'own', perms: ['read'] }, staff: { level: 'assigned', perms: ['read'] }, agent: { level: 'service', perms: ['read', 'write'] }, note: 'Customer view is redacted; writes are append-only.' },
  { entity: 'emergency_stop_state', customer: { level: 'own', perms: ['read', 'write'] }, staff: { level: 'assigned', perms: ['read', 'write', 'approve'] }, agent: { level: 'reference', perms: ['read'] }, note: 'Agents must read stop state but cannot set or clear it.' },
];

export const rlsPolicyRules = [
  'Customer policies match on organisation membership; no record is reachable without organisation_id.',
  'Staff policies require an active engagement assignment, not just a staff flag.',
  'Agent policies use a service identity bound to one engagement or run and are read/append only.',
  'Customer-visible flags are enforced at the row level, not only in the UI.',
  'Audit and evidence rows are append-only for agents and never hard-deleted by an application role.',
];

export const rlsMatrixNote = 'Proposed policy matrix only. No policies, tables or RLS rules are implemented by this document.';

export const sensitiveDataRules = {
  never: [
    'Plaintext customer passwords',
    'Reusable MFA codes',
    'Raw secret keys unless technically unavoidable and separately protected',
    'Unredacted sensitive tokens in normal evidence fields',
  ],
  recommendations: [
    'Temporary accounts',
    'Secret vault references',
    'Expiry',
    'Rotation and deletion after engagement',
  ],
  note: 'Do not design a custom plaintext secret store. Where credentials are required, reference an external vault.',
};

export const retentionClasses = [
  { name: 'Operational', icon: 'ri-folder-settings-line', desc: 'Engagement metadata.' },
  { name: 'Evidence', icon: 'ri-file-shield-2-line', desc: 'Security evidence requiring defined retention.' },
  { name: 'Reports', icon: 'ri-file-chart-line', desc: 'Customer deliverables.' },
  { name: 'Audit', icon: 'ri-history-line', desc: 'Longer-lived audit information.' },
  { name: 'Temporary', icon: 'ri-delete-bin-6-line', desc: 'Agent intermediate output.' },
];

export const retentionNote = 'Final legal retention periods are not defined here. Retention is configurable so policy can be set later without schema changes.';

export const findingVersioning = {
  concept: [
    { table: 'finding', role: 'Current canonical state' },
    { table: 'finding_history', role: 'Append-only record of meaningful changes' },
  ],
  changes: ['Severity change', 'Validation', 'Remediation state', 'Risk acceptance', 'Retest result'],
  note: 'History is append-only so the current state stays clean while every consequential change remains reconstructable.',
};

export const suggestedIndexes = [
  'organisation_id',
  'engagement_id',
  'run_id',
  'status',
  'severity',
  'finding_reference',
  'created_at',
  'asset hostname / domain',
  'watch detected_at',
];

export const foreignKeyBehaviour = {
  restrict: ['Scope versions', 'Approvals', 'Agent tasks', 'Findings', 'Evidence', 'Reports', 'Audit events'],
  prefer: [
    { method: 'RESTRICT', desc: 'Block deletion of a parent that still has dependent security records.' },
    { method: 'Soft deletion', desc: 'Mark records as archived or ended instead of deleting them.' },
    { method: 'Archival', desc: 'Move completed or expired records into an archived state where appropriate.' },
  ],
  note: 'Security evidence, reports and audit records should not disappear automatically because a parent record was accidentally deleted.',
};

export const implementationOrder = [
  { phase: 'Phase 1', title: 'Engagements, organisations & assets', desc: 'Foundation records and tenant isolation roots.' },
  { phase: 'Phase 2', title: 'Scope & approvals', desc: 'Versioned scope, explicit asset permissions and approval gates.' },
  { phase: 'Phase 3', title: 'Runs, agents, tasks & scope validation', desc: 'Execution records and the proof that out-of-scope requests are blocked.' },
  { phase: 'Phase 4', title: 'Findings & evidence', desc: 'Canonical findings with traceable supporting evidence.' },
  { phase: 'Phase 5', title: 'Attack paths & remediation', desc: 'Grouping, ownership and remediation workflow.' },
  { phase: 'Phase 6', title: 'Retests & reports', desc: 'Verification outcomes and versioned customer deliverables.' },
  { phase: 'Phase 7', title: 'Security Watch', desc: 'Authorised ongoing monitoring and material-change review.' },
  { phase: 'Phase 8', title: 'Audit hardening & retention', desc: 'Immutable audit events and configurable retention policy.' },
];

export const unresolvedQuestions = [
  'Should engagement, run and finding state be separate columns rather than one overloaded status field?',
  'Does emergency stop belong only on engagement_scope and assessment_runs, or a dedicated control table (recommended)?',
  'Are report findings stored as a normalised snapshot or an immutable finding version?',
  'Which records require soft deletion versus hard deletion, and who can approve a deletion?',
  'How are agent service identities represented in the existing database authority model?',
  'Which existing DFP tables already satisfy parts of this design before any new schema is created?',
];