import type {
  ViewKey,
  DemoSite,
  DemoGuard,
  DemoIncident,
  RotaShift,
  ComplianceRecord,
  ActivityEvent,
  IntelligenceInsight,
  ClientReport,
  TourStep,
} from './types';

export const SITES: DemoSite[] = [
  {
    id: 'apex',
    name: 'Apex Distribution Centre',
    client: 'Apex Logistics Ltd',
    status: 'healthy',
    guardsOnDuty: 4,
    guardsRequired: 4,
    shiftStart: '06:00',
    shiftEnd: '18:00',
    nextPatrolDue: '14:22',
    patrolOverdue: false,
    patrolCheckpoints: [
      { id: 'a1', name: 'Main Gate', completed: true },
      { id: 'a2', name: 'Loading Bay A', completed: true },
      { id: 'a3', name: 'Loading Bay B', completed: true },
      { id: 'a4', name: 'Staff Car Park', completed: false },
      { id: 'a5', name: 'Perimeter Fence', completed: false },
    ],
    instructions: [
      'All vehicle access through Main Gate only',
      'Loading Bay B closed after 17:00',
      'Staff Car Park barrier operational 06:00-22:00',
    ],
    hasOpenIncident: false,
  },
  {
    id: 'riverside',
    name: 'Riverside Retail Park',
    client: 'Riverside Estates',
    status: 'healthy',
    guardsOnDuty: 2,
    guardsRequired: 2,
    shiftStart: '08:00',
    shiftEnd: '20:00',
    nextPatrolDue: '14:44',
    patrolOverdue: false,
    patrolCheckpoints: [
      { id: 'r1', name: 'North Entrance', completed: true },
      { id: 'r2', name: 'South Entrance', completed: true },
      { id: 'r3', name: 'Underground Car Park', completed: true },
      { id: 'r4', name: 'Service Yard', completed: false },
    ],
    instructions: [
      'Retail units open 08:00-20:00',
      'Car park exits monitored by ANPR',
      'Service yard deliveries 06:00-11:00 only',
    ],
    hasOpenIncident: false,
  },
  {
    id: 'northgate',
    name: 'Northgate Offices',
    client: 'Northgate Properties',
    status: 'healthy',
    guardsOnDuty: 3,
    guardsRequired: 3,
    shiftStart: '07:00',
    shiftEnd: '19:00',
    nextPatrolDue: '15:10',
    patrolOverdue: false,
    patrolCheckpoints: [
      { id: 'n1', name: 'Reception', completed: true },
      { id: 'n2', name: 'Floors 1-3', completed: true },
      { id: 'n3', name: 'Floors 4-6', completed: false },
      { id: 'n4', name: 'Basement Car Park', completed: false },
    ],
    instructions: [
      'Reception desk manned 07:00-19:00',
      'Visitor passes required for floors 3+',
      'Basement accessible to permit holders only',
    ],
    hasOpenIncident: false,
  },
  {
    id: 'westfield',
    name: 'Westfield Construction Site',
    client: 'Westfield Developments',
    status: 'attention',
    guardsOnDuty: 1,
    guardsRequired: 2,
    shiftStart: '08:00',
    shiftEnd: '20:00',
    nextPatrolDue: '14:30',
    patrolOverdue: true,
    patrolCheckpoints: [
      { id: 'w1', name: 'Main Entrance', completed: true },
      { id: 'w2', name: 'Loading Bay', completed: true },
      { id: 'w3', name: 'East Perimeter', completed: true },
      { id: 'w4', name: 'Plant Area', completed: true },
      { id: 'w5', name: 'Rear Gate', completed: false },
    ],
    instructions: [
      'Main entrance controlled access with ID check',
      'Perimeter patrol every 60 minutes',
      'Delivery gate closes at 18:00',
      'Plant area locked outside working hours',
    ],
    hasOpenIncident: true,
  },
  {
    id: 'harbour',
    name: 'Harbour Logistics',
    client: 'Harbour Group',
    status: 'healthy',
    guardsOnDuty: 5,
    guardsRequired: 5,
    shiftStart: '06:00',
    shiftEnd: '18:00',
    nextPatrolDue: '14:58',
    patrolOverdue: false,
    patrolCheckpoints: [
      { id: 'h1', name: 'Gatehouse', completed: true },
      { id: 'h2', name: 'Warehouse A', completed: true },
      { id: 'h3', name: 'Warehouse B', completed: true },
      { id: 'h4', name: 'Container Yard', completed: false },
      { id: 'h5', name: 'Fuel Station', completed: false },
      { id: 'h6', name: 'Admin Building', completed: false },
    ],
    instructions: [
      'Gatehouse staffed 24/7',
      'Container yard CCTV monitored',
      'Fuel station access restricted to authorised drivers',
      'Night shift handover at 18:00',
    ],
    hasOpenIncident: false,
  },
  {
    id: 'citypoint',
    name: 'CityPoint Apartments',
    client: 'CityPoint Management',
    status: 'healthy',
    guardsOnDuty: 3,
    guardsRequired: 3,
    shiftStart: '08:00',
    shiftEnd: '20:00',
    nextPatrolDue: '15:32',
    patrolOverdue: false,
    patrolCheckpoints: [
      { id: 'c1', name: 'Main Lobby', completed: true },
      { id: 'c2', name: 'Resident Floors', completed: true },
      { id: 'c3', name: 'Gym & Pool Area', completed: false },
      { id: 'c4', name: 'Underground Parking', completed: false },
    ],
    instructions: [
      'Concierge desk manned 08:00-22:00',
      'Resident fob access to all common areas',
      'Visitor sign-in required',
      'Pool area closes at 22:00',
    ],
    hasOpenIncident: false,
  },
];

export const GUARDS: DemoGuard[] = [
  {
    id: 'guard-marcus',
    name: 'Marcus Reed',
    role: 'Door Supervisor',
    initials: 'MR',
    status: 'on_duty',
    currentSiteId: 'riverside',
    shiftStart: '08:00',
    shiftEnd: '20:00',
    compliance: 'current',
    lastPatrol: '13:44',
    siaLicence: 'DEMO-SIA-48291',
  },
  {
    id: 'guard-daniel',
    name: 'Daniel Price',
    role: 'Door Supervisor',
    initials: 'DP',
    status: 'on_duty',
    currentSiteId: 'westfield',
    shiftStart: '08:00',
    shiftEnd: '20:00',
    compliance: 'current',
    lastPatrol: '13:31',
    siaLicence: 'DEMO-SIA-78342',
  },
  {
    id: 'guard-aisha',
    name: 'Aisha Khan',
    role: 'Security Officer',
    initials: 'AK',
    status: 'on_duty',
    currentSiteId: 'riverside',
    shiftStart: '08:00',
    shiftEnd: '20:00',
    compliance: 'expiring_soon',
    lastPatrol: '13:20',
    siaLicence: 'DEMO-SIA-62901',
  },
  {
    id: 'guard-sophie',
    name: 'Sophie Grant',
    role: 'Security Officer',
    initials: 'SG',
    status: 'on_duty',
    currentSiteId: 'northgate',
    shiftStart: '07:00',
    shiftEnd: '19:00',
    compliance: 'current',
    lastPatrol: '13:50',
    siaLicence: 'DEMO-SIA-39017',
  },
  {
    id: 'guard-james',
    name: 'James Carter',
    role: 'Door Supervisor',
    initials: 'JC',
    status: 'on_duty',
    currentSiteId: 'apex',
    shiftStart: '06:00',
    shiftEnd: '18:00',
    compliance: 'current',
    lastPatrol: '13:28',
    siaLicence: 'DEMO-SIA-14588',
  },
  {
    id: 'guard-elena',
    name: 'Elena Vasquez',
    role: 'Site Security',
    initials: 'EV',
    status: 'on_duty',
    currentSiteId: 'harbour',
    shiftStart: '06:00',
    shiftEnd: '18:00',
    compliance: 'current',
    lastPatrol: '13:55',
    siaLicence: 'DEMO-SIA-90234',
  },
  {
    id: 'guard-tom',
    name: 'Tom Harrington',
    role: 'Security Officer',
    initials: 'TH',
    status: 'on_duty',
    currentSiteId: 'apex',
    shiftStart: '06:00',
    shiftEnd: '18:00',
    compliance: 'current',
    lastPatrol: '13:12',
    siaLicence: 'DEMO-SIA-56712',
  },
  {
    id: 'guard-rachel',
    name: 'Rachel Okonkwo',
    role: 'Security Officer',
    initials: 'RO',
    status: 'on_duty',
    currentSiteId: 'northgate',
    shiftStart: '07:00',
    shiftEnd: '19:00',
    compliance: 'expiring_soon',
    lastPatrol: '13:38',
    siaLicence: 'DEMO-SIA-33409',
  },
  {
    id: 'guard-david',
    name: 'David Chen',
    role: 'Site Security',
    initials: 'DC',
    status: 'on_duty',
    currentSiteId: 'harbour',
    shiftStart: '06:00',
    shiftEnd: '18:00',
    compliance: 'current',
    lastPatrol: '13:05',
    siaLicence: 'DEMO-SIA-22187',
  },
  {
    id: 'guard-maria',
    name: 'Maria Santos',
    role: 'Door Supervisor',
    initials: 'MS',
    status: 'on_duty',
    currentSiteId: 'apex',
    shiftStart: '06:00',
    shiftEnd: '18:00',
    compliance: 'current',
    lastPatrol: '13:48',
    siaLicence: 'DEMO-SIA-77321',
  },
  {
    id: 'guard-liam',
    name: 'Liam O\'Brien',
    role: 'Security Officer',
    initials: 'LO',
    status: 'on_duty',
    currentSiteId: 'citypoint',
    shiftStart: '08:00',
    shiftEnd: '20:00',
    compliance: 'current',
    lastPatrol: '13:15',
    siaLicence: 'DEMO-SIA-44566',
  },
  {
    id: 'guard-fatima',
    name: 'Fatima Hassan',
    role: 'Security Officer',
    initials: 'FH',
    status: 'on_duty',
    currentSiteId: 'citypoint',
    shiftStart: '08:00',
    shiftEnd: '20:00',
    compliance: 'current',
    lastPatrol: '13:22',
    siaLicence: 'DEMO-SIA-98901',
  },
  {
    id: 'guard-owen',
    name: 'Owen Davies',
    role: 'Door Supervisor',
    initials: 'OD',
    status: 'on_duty',
    currentSiteId: 'harbour',
    shiftStart: '06:00',
    shiftEnd: '18:00',
    compliance: 'current',
    lastPatrol: '13:33',
    siaLicence: 'DEMO-SIA-11234',
  },
  {
    id: 'guard-anika',
    name: 'Anika Patel',
    role: 'Security Officer',
    initials: 'AP',
    status: 'on_duty',
    currentSiteId: 'northgate',
    shiftStart: '07:00',
    shiftEnd: '19:00',
    compliance: 'current',
    lastPatrol: '13:47',
    siaLicence: 'DEMO-SIA-65092',
  },
  {
    id: 'guard-george',
    name: 'George Thompson',
    role: 'Site Security',
    initials: 'GT',
    status: 'on_duty',
    currentSiteId: 'citypoint',
    shiftStart: '08:00',
    shiftEnd: '20:00',
    compliance: 'current',
    lastPatrol: '13:08',
    siaLicence: 'DEMO-SIA-33871',
  },
  {
    id: 'guard-natasha',
    name: 'Natasha Blake',
    role: 'Security Officer',
    initials: 'NB',
    status: 'on_duty',
    currentSiteId: 'apex',
    shiftStart: '06:00',
    shiftEnd: '18:00',
    compliance: 'action_required',
    lastPatrol: '13:42',
    siaLicence: 'DEMO-SIA-19843',
  },
  {
    id: 'guard-callum',
    name: 'Callum Wright',
    role: 'Door Supervisor',
    initials: 'CW',
    status: 'on_duty',
    currentSiteId: 'harbour',
    shiftStart: '06:00',
    shiftEnd: '18:00',
    compliance: 'current',
    lastPatrol: '13:16',
    siaLicence: 'DEMO-SIA-87023',
  },
  {
    id: 'guard-amara',
    name: 'Amara Eze',
    role: 'Security Officer',
    initials: 'AE',
    status: 'on_duty',
    currentSiteId: 'harbour',
    shiftStart: '06:00',
    shiftEnd: '18:00',
    compliance: 'current',
    lastPatrol: '13:51',
    siaLicence: 'DEMO-SIA-55409',
  },
  {
    id: 'guard-ben',
    name: 'Ben Marshall',
    role: 'Site Security',
    initials: 'BM',
    status: 'off_duty',
    currentSiteId: null,
    shiftStart: '20:00',
    shiftEnd: '08:00',
    compliance: 'current',
    lastPatrol: null,
    siaLicence: 'DEMO-SIA-44321',
  },
  {
    id: 'guard-karen',
    name: 'Karen Mitchell',
    role: 'Security Officer',
    initials: 'KM',
    status: 'off_duty',
    currentSiteId: null,
    shiftStart: '20:00',
    shiftEnd: '08:00',
    compliance: 'current',
    lastPatrol: null,
    siaLicence: 'DEMO-SIA-77654',
  },
];

export const INCIDENT: DemoIncident = {
  id: 'INC-1048',
  title: 'Unauthorised vehicle at service entrance',
  description: 'A white transit van entered via the service entrance without prior authorisation. Driver left vehicle unattended near the loading area. Vehicle registration recorded.',
  priority: 'medium',
  siteId: 'westfield',
  reportedBy: 'Daniel Price',
  reportedAt: '14:31',
  status: 'open',
  timeline: [
    { time: '14:31', message: 'Incident created by Daniel Price', type: 'created' },
    { time: '14:33', message: 'Control room notified', type: 'update' },
    { time: '14:35', message: 'Client contact prepared', type: 'action' },
  ],
};

export const ROTA_SHIFTS: RotaShift[] = [
  {
    id: 'rota-riverside-day',
    siteId: 'riverside',
    siteName: 'Riverside Retail Park',
    start: '08:00',
    end: '20:00',
    assignedGuards: ['guard-marcus', 'guard-aisha'],
    requiredGuards: 2,
    status: 'covered',
  },
  {
    id: 'rota-northgate-day',
    siteId: 'northgate',
    siteName: 'Northgate Offices',
    start: '07:00',
    end: '19:00',
    assignedGuards: ['guard-sophie'],
    requiredGuards: 2,
    status: 'attention',
  },
  {
    id: 'rota-westfield-day',
    siteId: 'westfield',
    siteName: 'Westfield Construction Site',
    start: '08:00',
    end: '20:00',
    assignedGuards: ['guard-daniel'],
    requiredGuards: 2,
    status: 'attention',
  },
  {
    id: 'rota-apex-day',
    siteId: 'apex',
    siteName: 'Apex Distribution Centre',
    start: '06:00',
    end: '18:00',
    assignedGuards: ['guard-james', 'guard-tom', 'guard-maria', 'guard-natasha'],
    requiredGuards: 4,
    status: 'covered',
  },
  {
    id: 'rota-harbour-day',
    siteId: 'harbour',
    siteName: 'Harbour Logistics',
    start: '06:00',
    end: '18:00',
    assignedGuards: ['guard-elena', 'guard-david', 'guard-owen', 'guard-callum', 'guard-amara'],
    requiredGuards: 5,
    status: 'covered',
  },
  {
    id: 'rota-harbour-night',
    siteId: 'harbour',
    siteName: 'Harbour Logistics',
    start: '20:00',
    end: '08:00',
    assignedGuards: [],
    requiredGuards: 3,
    status: 'unassigned',
  },
  {
    id: 'rota-citypoint-day',
    siteId: 'citypoint',
    siteName: 'CityPoint Apartments',
    start: '08:00',
    end: '20:00',
    assignedGuards: ['guard-liam', 'guard-fatima', 'guard-george'],
    requiredGuards: 3,
    status: 'covered',
  },
];

export const COMPLIANCE_RECORDS: ComplianceRecord[] = [
  { id: 'comp-1', guardId: 'guard-aisha', guardName: 'Aisha Khan', type: 'Site Induction', status: 'expiring_soon', expiresIn: '6 days', detail: 'Riverside Retail Park site induction expires in 6 days.' },
  { id: 'comp-2', guardId: 'guard-rachel', guardName: 'Rachel Okonkwo', type: 'First Aid', status: 'expiring_soon', expiresIn: '14 days', detail: 'First Aid at Work certificate expires in 14 days.' },
  { id: 'comp-3', guardId: 'guard-natasha', guardName: 'Natasha Blake', type: 'SIA Licence', status: 'action_required', expiresIn: '2 days', detail: 'SIA Door Supervisor licence expires in 2 days. Renewal required.' },
  { id: 'comp-4', guardId: 'guard-marcus', guardName: 'Marcus Reed', type: 'SIA Licence', status: 'current', expiresIn: null, detail: 'Valid until 2027-03-15' },
  { id: 'comp-5', guardId: 'guard-marcus', guardName: 'Marcus Reed', type: 'Right to Work', status: 'current', expiresIn: null, detail: 'Verified 2026-01-10' },
  { id: 'comp-6', guardId: 'guard-marcus', guardName: 'Marcus Reed', type: 'Training', status: 'current', expiresIn: null, detail: 'Conflict Management completed 2026-06' },
  { id: 'comp-7', guardId: 'guard-daniel', guardName: 'Daniel Price', type: 'SIA Licence', status: 'current', expiresIn: null, detail: 'Valid until 2028-01-22' },
  { id: 'comp-8', guardId: 'guard-daniel', guardName: 'Daniel Price', type: 'Site Induction', status: 'current', expiresIn: null, detail: 'Westfield Construction induction valid.' },
  { id: 'comp-9', guardId: 'guard-sophie', guardName: 'Sophie Grant', type: 'SIA Licence', status: 'current', expiresIn: null, detail: 'Valid until 2027-08-03' },
  { id: 'comp-10', guardId: 'guard-sophie', guardName: 'Sophie Grant', type: 'First Aid', status: 'current', expiresIn: null, detail: 'First Aid at Work valid until 2027-11' },
  { id: 'comp-11', guardId: 'guard-elena', guardName: 'Elena Vasquez', type: 'SIA Licence', status: 'current', expiresIn: null, detail: 'Valid until 2027-05-18' },
  { id: 'comp-12', guardId: 'guard-james', guardName: 'James Carter', type: 'SIA Licence', status: 'current', expiresIn: null, detail: 'Valid until 2028-02-10' },
];

export const INITIAL_ACTIVITIES: ActivityEvent[] = [
  { id: 'act-1', time: '14:42', message: 'Marcus Reed checked in at Riverside Retail Park', type: 'checkin', guardId: 'guard-marcus', siteId: 'riverside' },
  { id: 'act-2', time: '14:38', message: 'Patrol completed at Apex Distribution Centre', type: 'patrol', siteId: 'apex' },
  { id: 'act-3', time: '14:31', message: 'Incident INC-1048 logged at Westfield Construction', type: 'incident', siteId: 'westfield' },
  { id: 'act-4', time: '14:22', message: 'Shift handover complete at Northgate Offices', type: 'handover', siteId: 'northgate' },
  { id: 'act-5', time: '14:15', message: 'James Carter completed patrol at Apex Distribution Centre', type: 'patrol', guardId: 'guard-james', siteId: 'apex' },
  { id: 'act-6', time: '14:08', message: 'Elena Vasquez started patrol at Harbour Logistics', type: 'patrol', guardId: 'guard-elena', siteId: 'harbour' },
  { id: 'act-7', time: '14:02', message: 'Control room shift change complete', type: 'system' },
  { id: 'act-8', time: '13:58', message: 'Scheduled maintenance: CityPoint CCTV system operational', type: 'system', siteId: 'citypoint' },
];

export const INITIAL_INSIGHTS: IntelligenceInsight[] = [
  {
    id: 'insight-1',
    category: 'Patrol Risk',
    title: 'Westfield rear checkpoint overdue',
    detail: 'Rear Gate patrol at Westfield Construction was due at 14:30. Current time: overdue.',
    action: 'Review patrol status.',
    resolved: false,
  },
  {
    id: 'insight-2',
    category: 'Rota Risk',
    title: 'Tonight\'s Harbour Logistics shift unassigned',
    detail: 'Night shift (20:00-08:00) has 0 of 3 guards assigned.',
    action: 'Assign cover.',
    resolved: false,
  },
  {
    id: 'insight-3',
    category: 'Compliance',
    title: 'Two items require attention within 14 days',
    detail: 'Aisha Khan site induction (6 days). Rachel Okonkwo First Aid (14 days).',
    action: 'Review compliance.',
    resolved: false,
  },
];

export const CLIENT_REPORTS: ClientReport[] = [
  {
    siteId: 'westfield',
    siteName: 'Westfield Construction Site',
    guardCoverage: 50,
    patrolsCompleted: 4,
    patrolsTotal: 5,
    incidentsResolved: 0,
    escalations: 0,
    status: 'attention',
  },
  {
    siteId: 'apex',
    siteName: 'Apex Distribution Centre',
    guardCoverage: 100,
    patrolsCompleted: 3,
    patrolsTotal: 5,
    incidentsResolved: 0,
    escalations: 0,
    status: 'healthy',
  },
];

export const TOUR_STEPS: TourStep[] = [
  {
    title: 'Read the operation',
    instruction: 'See every active site from one screen. Check guard coverage, patrol status and site health at a glance.',
    view: 'command',
  },
  {
    title: 'Find the risk',
    instruction: 'Locate the overdue patrol at Westfield Construction. The system flags what needs attention.',
    view: 'sites',
  },
  {
    title: 'Resolve the patrol',
    instruction: 'Complete the overdue patrol checkpoint. Watch the entire system update — site status, alerts and activity feed.',
    view: 'patrols',
  },
  {
    title: 'Handle an incident',
    instruction: 'Review and close the open incident at Westfield Construction. The operational picture improves instantly.',
    view: 'incidents',
  },
  {
    title: 'Protect tomorrow\'s rota',
    instruction: 'Fill the uncovered night shift at Harbour Logistics. Coverage improves from attention to covered.',
    view: 'rota',
  },
  {
    title: 'Check compliance',
    instruction: 'Find upcoming workforce compliance requirements. Two items need attention within two weeks.',
    view: 'compliance',
  },
  {
    title: 'See what the client sees',
    instruction: 'Preview the service from the client\'s side — site status, patrol completion and incident summaries.',
    view: 'clients',
  },
];

export const NAV_ITEMS: { key: ViewKey; label: string; icon: string }[] = [
  { key: 'command', label: 'Command Centre', icon: 'ri-dashboard-line' },
  { key: 'sites', label: 'Sites', icon: 'ri-building-line' },
  { key: 'guards', label: 'Guards', icon: 'ri-shield-user-line' },
  { key: 'patrols', label: 'Patrols', icon: 'ri-footprint-line' },
  { key: 'incidents', label: 'Incidents', icon: 'ri-alert-line' },
  { key: 'rota', label: 'Rota', icon: 'ri-calendar-check-line' },
  { key: 'compliance', label: 'Compliance', icon: 'ri-file-shield-2-line' },
  { key: 'clients', label: 'Clients', icon: 'ri-user-voice-line' },
];
