export type EventCategory =
  | 'assignment' | 'mention' | 'approval' | 'deadline'
  | 'client' | 'project' | 'task' | 'finance'
  | 'operations' | 'automation' | 'uat' | 'pbx'
  | 'content' | 'security' | 'system';

export type EventSeverity = 'info' | 'success' | 'warning' | 'high' | 'critical';

export type AuditResult = 'success' | 'denied' | 'failed' | 'partial';

export type SourceSystem = 'human' | 'service' | 'n8n' | 'edge_function' | 'ai_agent' | 'external' | 'scheduler';

export interface EventDefinition {
  eventType: string;
  label: string;
  category: EventCategory;
  defaultSeverity: EventSeverity;
  requiresActivity: boolean;
  requiresAudit: boolean;
  dedupWindowMinutes: number;
  externalDeliveryEligible: boolean;
  recipientRule: string;
}

export const EVENT_CATALOGUE: Record<string, EventDefinition> = {
  'lead.created': {
    eventType: 'lead.created', label: 'Lead Created', category: 'client', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: true,
    recipientRule: 'owner',
  },
  'lead.assigned': {
    eventType: 'lead.assigned', label: 'Lead Assigned', category: 'assignment', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: true,
    recipientRule: 'assignee',
  },
  'lead.converted': {
    eventType: 'lead.converted', label: 'Lead Converted', category: 'client', defaultSeverity: 'success',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'client.created': {
    eventType: 'client.created', label: 'Client Created', category: 'client', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: true,
    recipientRule: 'owner',
  },
  'client.archived': {
    eventType: 'client.archived', label: 'Client Archived', category: 'client', defaultSeverity: 'warning',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'project.created': {
    eventType: 'project.created', label: 'Project Created', category: 'project', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: true,
    recipientRule: 'owner',
  },
  'project.status_changed': {
    eventType: 'project.status_changed', label: 'Project Status Changed', category: 'project', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: true,
    recipientRule: 'owner',
  },
  'project.at_risk': {
    eventType: 'project.at_risk', label: 'Project At Risk', category: 'project', defaultSeverity: 'high',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 1440, externalDeliveryEligible: true,
    recipientRule: 'owner',
  },
  'task.overdue': {
    eventType: 'task.overdue', label: 'Task Overdue', category: 'deadline', defaultSeverity: 'high',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 1440, externalDeliveryEligible: true,
    recipientRule: 'assignee',
  },
  'milestone.completed': {
    eventType: 'milestone.completed', label: 'Milestone Completed', category: 'project', defaultSeverity: 'success',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: true,
    recipientRule: 'owner',
  },
  'milestone.overdue': {
    eventType: 'milestone.overdue', label: 'Milestone Overdue', category: 'deadline', defaultSeverity: 'high',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 1440, externalDeliveryEligible: true,
    recipientRule: 'owner',
  },
  'invoice.issued': {
    eventType: 'invoice.issued', label: 'Invoice Issued', category: 'finance', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: true,
    recipientRule: 'client_owner',
  },
  'invoice.paid': {
    eventType: 'invoice.paid', label: 'Invoice Paid', category: 'finance', defaultSeverity: 'success',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'finance_approver',
  },
  'invoice.overdue': {
    eventType: 'invoice.overdue', label: 'Invoice Overdue', category: 'finance', defaultSeverity: 'high',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 1440, externalDeliveryEligible: true,
    recipientRule: 'client_owner',
  },
  'invoice.approval_requested': {
    eventType: 'invoice.approval_requested', label: 'Invoice Approval Requested', category: 'approval', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: true,
    recipientRule: 'finance_approver',
  },
  'payment.recorded': {
    eventType: 'payment.recorded', label: 'Payment Recorded', category: 'finance', defaultSeverity: 'success',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'finance_approver',
  },
  'incident.declared': {
    eventType: 'incident.declared', label: 'Incident Declared', category: 'operations', defaultSeverity: 'critical',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: true,
    recipientRule: 'incident_commander',
  },
  'incident.resolved': {
    eventType: 'incident.resolved', label: 'Incident Resolved', category: 'operations', defaultSeverity: 'success',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'incident_commander',
  },
  'automation.execution_failed': {
    eventType: 'automation.execution_failed', label: 'Automation Failed', category: 'automation', defaultSeverity: 'high',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 30, externalDeliveryEligible: true,
    recipientRule: 'owner',
  },
  'uat.feedback_submitted': {
    eventType: 'uat.feedback_submitted', label: 'UAT Feedback Submitted', category: 'uat', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: true,
    recipientRule: 'uat_owner',
  },
  'uat.critical_defect': {
    eventType: 'uat.critical_defect', label: 'Critical UAT Defect', category: 'uat', defaultSeverity: 'critical',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 60, externalDeliveryEligible: true,
    recipientRule: 'uat_owner',
  },
  'uat.project_created': {
    eventType: 'uat.project_created', label: 'UAT Project Created', category: 'uat', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'uat_owner',
  },
  'uat.environment_ready': {
    eventType: 'uat.environment_ready', label: 'UAT Environment Ready', category: 'uat', defaultSeverity: 'success',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'uat_owner',
  },
  'uat.job_opened': {
    eventType: 'uat.job_opened', label: 'UAT Job Opened', category: 'uat', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: true,
    recipientRule: 'uat_owner',
  },
  'uat.application_submitted': {
    eventType: 'uat.application_submitted', label: 'Tester Application Submitted', category: 'uat', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: true,
    recipientRule: 'uat_owner',
  },
  'uat.application_decided': {
    eventType: 'uat.application_decided', label: 'Tester Application Decided', category: 'uat', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'uat_owner',
  },
  'uat.assignment_offered': {
    eventType: 'uat.assignment_offered', label: 'UAT Assignment Offered', category: 'uat', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: true,
    recipientRule: 'assignee',
  },
  'uat.assignment_accepted': {
    eventType: 'uat.assignment_accepted', label: 'UAT Assignment Accepted', category: 'uat', defaultSeverity: 'success',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'uat_owner',
  },
  'uat.session_submitted': {
    eventType: 'uat.session_submitted', label: 'UAT Session Submitted', category: 'uat', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'uat_owner',
  },
  'uat.feedback_triaged': {
    eventType: 'uat.feedback_triaged', label: 'UAT Feedback Triaged', category: 'uat', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'uat_owner',
  },
  'uat.clarification_requested': {
    eventType: 'uat.clarification_requested', label: 'UAT Clarification Requested', category: 'uat', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: true,
    recipientRule: 'assignee',
  },
  'uat.resolution_recorded': {
    eventType: 'uat.resolution_recorded', label: 'UAT Resolution Recorded', category: 'uat', defaultSeverity: 'success',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'uat_owner',
  },
  'uat.retest_requested': {
    eventType: 'uat.retest_requested', label: 'UAT Retest Requested', category: 'uat', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: true,
    recipientRule: 'assignee',
  },
  'uat.retest_failed': {
    eventType: 'uat.retest_failed', label: 'UAT Retest Failed', category: 'uat', defaultSeverity: 'warning',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: true,
    recipientRule: 'uat_owner',
  },
  'uat.retest_passed': {
    eventType: 'uat.retest_passed', label: 'UAT Retest Passed', category: 'uat', defaultSeverity: 'success',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'uat_owner',
  },
  'uat.approval_decided': {
    eventType: 'uat.approval_decided', label: 'UAT Approval Decided', category: 'uat', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'uat_owner',
  },
  'pbx.route_activated': {
    eventType: 'pbx.route_activated', label: 'PBX Route Activated', category: 'pbx', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'pbx_owner',
  },
  'pbx.service_failure': {
    eventType: 'pbx.service_failure', label: 'PBX Service Failure', category: 'pbx', defaultSeverity: 'critical',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 15, externalDeliveryEligible: true,
    recipientRule: 'pbx_owner',
  },
  'pbx.tenant_created': {
    eventType: 'pbx.tenant_created', label: 'PBX Tenant Created', category: 'pbx', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'pbx.tenant_suspended': {
    eventType: 'pbx.tenant_suspended', label: 'PBX Tenant Suspended', category: 'pbx', defaultSeverity: 'warning',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'pbx.number_assigned': {
    eventType: 'pbx.number_assigned', label: 'PBX Number Assigned', category: 'pbx', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'pbx_owner',
  },
  'pbx.webhook_received': {
    eventType: 'pbx.webhook_received', label: 'PBX Webhook Received', category: 'pbx', defaultSeverity: 'info',
    requiresActivity: false, requiresAudit: false, dedupWindowMinutes: 1, externalDeliveryEligible: false,
    recipientRule: 'pbx_owner',
  },
  'pbx.webhook_failed': {
    eventType: 'pbx.webhook_failed', label: 'PBX Webhook Failed', category: 'pbx', defaultSeverity: 'high',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 15, externalDeliveryEligible: true,
    recipientRule: 'pbx_owner',
  },
  'pbx.sync_completed': {
    eventType: 'pbx.sync_completed', label: 'PBX Provider Sync Completed', category: 'pbx', defaultSeverity: 'success',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'pbx_owner',
  },
  'pbx.sync_failed': {
    eventType: 'pbx.sync_failed', label: 'PBX Provider Sync Failed', category: 'pbx', defaultSeverity: 'high',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 30, externalDeliveryEligible: true,
    recipientRule: 'pbx_owner',
  },
  'pbx.cost_updated': {
    eventType: 'pbx.cost_updated', label: 'PBX Cost Data Updated', category: 'pbx', defaultSeverity: 'info',
    requiresActivity: false, requiresAudit: false, dedupWindowMinutes: 60, externalDeliveryEligible: false,
    recipientRule: 'pbx_owner',
  },
  'content.published': {
    eventType: 'content.published', label: 'Content Published', category: 'content', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'content_reviewer',
  },
  'staff.permission_changed': {
    eventType: 'staff.permission_changed', label: 'Staff Permission Changed', category: 'security', defaultSeverity: 'high',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'staff.invited': {
    eventType: 'staff.invited', label: 'Staff Invited', category: 'security', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: true,
    recipientRule: 'assignee',
  },
  'staff.suspended': {
    eventType: 'staff.suspended', label: 'Staff Member Suspended', category: 'security', defaultSeverity: 'critical',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'staff.invitation_sent': {
    eventType: 'staff.invitation_sent', label: 'Staff Invitation Sent', category: 'security', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: true,
    recipientRule: 'assignee',
  },
  'staff.invitation_accepted': {
    eventType: 'staff.invitation_accepted', label: 'Staff Invitation Accepted', category: 'security', defaultSeverity: 'success',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'staff.activated': {
    eventType: 'staff.activated', label: 'Staff Account Activated', category: 'security', defaultSeverity: 'success',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'staff.role_changed': {
    eventType: 'staff.role_changed', label: 'Staff Role Changed', category: 'security', defaultSeverity: 'high',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'staff.permission_set_changed': {
    eventType: 'staff.permission_set_changed', label: 'Permission Set Changed', category: 'security', defaultSeverity: 'high',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'staff.temp_access_granted': {
    eventType: 'staff.temp_access_granted', label: 'Temporary Access Granted', category: 'security', defaultSeverity: 'warning',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'staff.temp_access_expired': {
    eventType: 'staff.temp_access_expired', label: 'Temporary Access Expired', category: 'security', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'staff.access_requested': {
    eventType: 'staff.access_requested', label: 'Access Request Submitted', category: 'security', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: true,
    recipientRule: 'owner',
  },
  'staff.access_approved': {
    eventType: 'staff.access_approved', label: 'Access Request Approved', category: 'security', defaultSeverity: 'warning',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'assignee',
  },
  'staff.review_completed': {
    eventType: 'staff.review_completed', label: 'Access Review Completed', category: 'security', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'staff.delegation_created': {
    eventType: 'staff.delegation_created', label: 'Delegation Created', category: 'security', defaultSeverity: 'warning',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'staff.offboarding_started': {
    eventType: 'staff.offboarding_started', label: 'Staff Offboarding Started', category: 'security', defaultSeverity: 'warning',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'staff.offboarding_completed': {
    eventType: 'staff.offboarding_completed', label: 'Staff Offboarding Completed', category: 'security', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'staff.service_account_rotated': {
    eventType: 'staff.service_account_rotated', label: 'Service Account Rotated', category: 'security', defaultSeverity: 'warning',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'deployment.failed': {
    eventType: 'deployment.failed', label: 'Deployment Failed', category: 'operations', defaultSeverity: 'critical',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 30, externalDeliveryEligible: true,
    recipientRule: 'owner',
  },
  'backup.failed': {
    eventType: 'backup.failed', label: 'Backup Failed', category: 'operations', defaultSeverity: 'high',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 1440, externalDeliveryEligible: true,
    recipientRule: 'owner',
  },
  'submission.received': {
    eventType: 'submission.received', label: 'Submission Received', category: 'client', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 5, externalDeliveryEligible: true,
    recipientRule: 'owner',
  },
  'mention.created': {
    eventType: 'mention.created', label: 'You Were Mentioned', category: 'mention', defaultSeverity: 'info',
    requiresActivity: false, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: true,
    recipientRule: 'mentioned',
  },
  'lead.stage_changed': {
    eventType: 'lead.stage_changed', label: 'Lead Stage Changed', category: 'client', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'lead.follow_up_due': {
    eventType: 'lead.follow_up_due', label: 'Lead Follow-up Due', category: 'deadline', defaultSeverity: 'warning',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 1440, externalDeliveryEligible: true,
    recipientRule: 'assignee',
  },
  'lead.follow_up_overdue': {
    eventType: 'lead.follow_up_overdue', label: 'Lead Follow-up Overdue', category: 'deadline', defaultSeverity: 'high',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 1440, externalDeliveryEligible: true,
    recipientRule: 'assignee',
  },
  'lead.merged': {
    eventType: 'lead.merged', label: 'Leads Merged', category: 'client', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'lead.archived': {
    eventType: 'lead.archived', label: 'Lead Archived', category: 'client', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'lead.note_added': {
    eventType: 'lead.note_added', label: 'Note Added to Lead', category: 'client', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'client.status_changed': {
    eventType: 'client.status_changed', label: 'Client Status Changed', category: 'client', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'account_manager',
  },
  'client.contact_added': {
    eventType: 'client.contact_added', label: 'Client Contact Added', category: 'client', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'account_manager',
  },
  'client.service_activated': {
    eventType: 'client.service_activated', label: 'Client Service Activated', category: 'client', defaultSeverity: 'success',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'account_manager',
  },
  'client.portal_granted': {
    eventType: 'client.portal_granted', label: 'Portal Access Granted', category: 'client', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'account_manager',
  },
  'client.onboarding_completed': {
    eventType: 'client.onboarding_completed', label: 'Client Onboarding Completed', category: 'client', defaultSeverity: 'success',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'account_manager',
  },
  'client.offboarding_started': {
    eventType: 'client.offboarding_started', label: 'Client Offboarding Started', category: 'client', defaultSeverity: 'warning',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'account_manager',
  },
  'client.note_added': {
    eventType: 'client.note_added', label: 'Internal Note Added', category: 'client', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'project.phase_updated': {
    eventType: 'project.phase_updated', label: 'Project Phase Updated', category: 'project', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'project.risk_identified': {
    eventType: 'project.risk_identified', label: 'Project Risk Identified', category: 'project', defaultSeverity: 'warning',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: true,
    recipientRule: 'owner',
  },
  'project.issue_logged': {
    eventType: 'project.issue_logged', label: 'Project Issue Logged', category: 'project', defaultSeverity: 'warning',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: true,
    recipientRule: 'owner',
  },
  'project.decision_made': {
    eventType: 'project.decision_made', label: 'Project Decision Made', category: 'project', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'project.change_requested': {
    eventType: 'project.change_requested', label: 'Change Request Submitted', category: 'project', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: true,
    recipientRule: 'owner',
  },
  'project.change_approved': {
    eventType: 'project.change_approved', label: 'Change Request Approved', category: 'project', defaultSeverity: 'success',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'project.file_uploaded': {
    eventType: 'project.file_uploaded', label: 'Project File Uploaded', category: 'project', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'project.team_changed': {
    eventType: 'project.team_changed', label: 'Project Team Changed', category: 'project', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'project.launch_ready': {
    eventType: 'project.launch_ready', label: 'Project Ready for Launch', category: 'project', defaultSeverity: 'success',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: true,
    recipientRule: 'owner',
  },
  'project.completed': {
    eventType: 'project.completed', label: 'Project Completed', category: 'project', defaultSeverity: 'success',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: true,
    recipientRule: 'owner',
  },
  'project.archived': {
    eventType: 'project.archived', label: 'Project Archived', category: 'project', defaultSeverity: 'warning',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'task.created': {
    eventType: 'task.created', label: 'Task Created', category: 'task', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: true,
    recipientRule: 'owner',
  },
  'task.status_changed': {
    eventType: 'task.status_changed', label: 'Task Status Changed', category: 'task', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: true,
    recipientRule: 'assignee',
  },
  'task.assigned': {
    eventType: 'task.assigned', label: 'Task Assigned', category: 'assignment', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: true,
    recipientRule: 'assignee',
  },
  'task.due_date_changed': {
    eventType: 'task.due_date_changed', label: 'Task Due Date Changed', category: 'deadline', defaultSeverity: 'warning',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: true,
    recipientRule: 'assignee',
  },
  'task.dependency_added': {
    eventType: 'task.dependency_added', label: 'Task Dependency Added', category: 'task', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'assignee',
  },
  'task.comment_added': {
    eventType: 'task.comment_added', label: 'Comment Added to Task', category: 'task', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: true,
    recipientRule: 'assignee',
  },
  'task.review_requested': {
    eventType: 'task.review_requested', label: 'Task Review Requested', category: 'task', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: true,
    recipientRule: 'reviewer',
  },
  'task.review_approved': {
    eventType: 'task.review_approved', label: 'Task Review Approved', category: 'task', defaultSeverity: 'success',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'assignee',
  },
  'task.completed': {
    eventType: 'task.completed', label: 'Task Completed', category: 'task', defaultSeverity: 'success',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'task.cancelled': {
    eventType: 'task.cancelled', label: 'Task Cancelled', category: 'task', defaultSeverity: 'warning',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'task.archived': {
    eventType: 'task.archived', label: 'Task Archived', category: 'task', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'task.recurrence_failed': {
    eventType: 'task.recurrence_failed', label: 'Recurring Task Generation Failed', category: 'automation', defaultSeverity: 'high',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 60, externalDeliveryEligible: true,
    recipientRule: 'owner',
  },
  'workflow.activated': {
    eventType: 'workflow.activated', label: 'Workflow Activated', category: 'automation', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'workflow.failed': {
    eventType: 'workflow.failed', label: 'Workflow Execution Failed', category: 'automation', defaultSeverity: 'high',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 30, externalDeliveryEligible: true,
    recipientRule: 'owner',
  },
  'workflow.retry_requested': {
    eventType: 'workflow.retry_requested', label: 'Workflow Retry Requested', category: 'automation', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'workflow.disabled': {
    eventType: 'workflow.disabled', label: 'Workflow Disabled', category: 'automation', defaultSeverity: 'warning',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: true,
    recipientRule: 'owner',
  },
  'workflow.archived': {
    eventType: 'workflow.archived', label: 'Workflow Archived', category: 'automation', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'webhook.failed': {
    eventType: 'webhook.failed', label: 'Webhook Delivery Failed', category: 'automation', defaultSeverity: 'high',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 15, externalDeliveryEligible: true,
    recipientRule: 'owner',
  },
  'webhook.activated': {
    eventType: 'webhook.activated', label: 'Webhook Activated', category: 'automation', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'schedule.missed': {
    eventType: 'schedule.missed', label: 'Schedule Missed', category: 'automation', defaultSeverity: 'high',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 1440, externalDeliveryEligible: true,
    recipientRule: 'owner',
  },
  'schedule.activated': {
    eventType: 'schedule.activated', label: 'Schedule Activated', category: 'automation', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'agent.approved': {
    eventType: 'agent.approved', label: 'AI Agent Approved', category: 'automation', defaultSeverity: 'success',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'agent.activated': {
    eventType: 'agent.activated', label: 'AI Agent Activated', category: 'automation', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'agent.failed': {
    eventType: 'agent.failed', label: 'AI Agent Run Failed', category: 'automation', defaultSeverity: 'high',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 30, externalDeliveryEligible: true,
    recipientRule: 'owner',
  },
  'agent.limit_warning': {
    eventType: 'agent.limit_warning', label: 'AI Agent Approaching Limit', category: 'automation', defaultSeverity: 'warning',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 60, externalDeliveryEligible: true,
    recipientRule: 'owner',
  },
  'agent.limit_reached': {
    eventType: 'agent.limit_reached', label: 'AI Agent Limit Reached', category: 'automation', defaultSeverity: 'high',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 30, externalDeliveryEligible: true,
    recipientRule: 'owner',
  },
  'approval.pending': {
    eventType: 'approval.pending', label: 'Automation Approval Required', category: 'automation', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: true,
    recipientRule: 'approver',
  },
  'approval.executed': {
    eventType: 'approval.executed', label: 'Approved Action Executed', category: 'automation', defaultSeverity: 'success',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'lockdown.activated': {
    eventType: 'lockdown.activated', label: 'Emergency Lockdown Activated', category: 'automation', defaultSeverity: 'critical',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: true,
    recipientRule: 'owner',
  },
  'invoice.draft_created': {
    eventType: 'invoice.draft_created', label: 'Invoice Draft Created', category: 'finance', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'invoice.approved': {
    eventType: 'invoice.approved', label: 'Invoice Approved', category: 'finance', defaultSeverity: 'success',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'invoice.cancelled': {
    eventType: 'invoice.cancelled', label: 'Invoice Cancelled', category: 'finance', defaultSeverity: 'warning',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'finance_approver',
  },
  'invoice.written_off': {
    eventType: 'invoice.written_off', label: 'Invoice Written Off', category: 'finance', defaultSeverity: 'high',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'finance_approver',
  },
  'invoice.archived': {
    eventType: 'invoice.archived', label: 'Invoice Archived', category: 'finance', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'payment.failed': {
    eventType: 'payment.failed', label: 'Payment Failed', category: 'finance', defaultSeverity: 'high',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 30, externalDeliveryEligible: true,
    recipientRule: 'finance_approver',
  },
  'payment.refunded': {
    eventType: 'payment.refunded', label: 'Payment Refunded', category: 'finance', defaultSeverity: 'warning',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'finance_approver',
  },
  'expense.submitted': {
    eventType: 'expense.submitted', label: 'Expense Submitted', category: 'finance', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: true,
    recipientRule: 'finance_approver',
  },
  'expense.approved': {
    eventType: 'expense.approved', label: 'Expense Approved', category: 'finance', defaultSeverity: 'success',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'credit.created': {
    eventType: 'credit.created', label: 'Credit Note Created', category: 'finance', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'finance_approver',
  },
  'dispute.opened': {
    eventType: 'dispute.opened', label: 'Invoice Dispute Opened', category: 'finance', defaultSeverity: 'high',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: true,
    recipientRule: 'finance_approver',
  },
  'tester.onboarding_approved': {
    eventType: 'tester.onboarding_approved', label: 'Tester Onboarding Approved', category: 'uat', defaultSeverity: 'success',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'uat_owner',
  },
  'tester.status_changed': {
    eventType: 'tester.status_changed', label: 'Tester Status Changed', category: 'uat', defaultSeverity: 'warning',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'uat_owner',
  },
  'tester.warning_issued': {
    eventType: 'tester.warning_issued', label: 'Tester Warning Issued', category: 'uat', defaultSeverity: 'high',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'uat_owner',
  },
  'tester.restriction_applied': {
    eventType: 'tester.restriction_applied', label: 'Tester Restriction Applied', category: 'uat', defaultSeverity: 'critical',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'uat_owner',
  },
  'tester.rating_added': {
    eventType: 'tester.rating_added', label: 'Tester Rating Added', category: 'uat', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'uat_owner',
  },
  'tester.payment_approved': {
    eventType: 'tester.payment_approved', label: 'Tester Payment Approved', category: 'uat', defaultSeverity: 'success',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'uat_owner',
  },
  'tester.payment_rejected': {
    eventType: 'tester.payment_rejected', label: 'Tester Payment Rejected', category: 'uat', defaultSeverity: 'warning',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'uat_owner',
  },
  'tester.payment_sent_to_finance': {
    eventType: 'tester.payment_sent_to_finance', label: 'Tester Payment Sent to Finance', category: 'uat', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'uat_owner',
  },
  'tester.payment_confirmed': {
    eventType: 'tester.payment_confirmed', label: 'Tester Payment Confirmed', category: 'uat', defaultSeverity: 'success',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'uat_owner',
  },
  'tester.payment_failed': {
    eventType: 'tester.payment_failed', label: 'Tester Payment Failed', category: 'uat', defaultSeverity: 'high',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 30, externalDeliveryEligible: true,
    recipientRule: 'uat_owner',
  },
  'tester.dispute_opened': {
    eventType: 'tester.dispute_opened', label: 'Tester Payment Dispute Opened', category: 'uat', defaultSeverity: 'high',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: true,
    recipientRule: 'uat_owner',
  },
  'tester.dispute_resolved': {
    eventType: 'tester.dispute_resolved', label: 'Tester Payment Dispute Resolved', category: 'uat', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'uat_owner',
  },
  'cms.revision_submitted': {
    eventType: 'cms.revision_submitted', label: 'CMS Revision Submitted', category: 'content', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: true,
    recipientRule: 'content_reviewer',
  },
  'cms.revision_approved': {
    eventType: 'cms.revision_approved', label: 'CMS Revision Approved', category: 'content', defaultSeverity: 'success',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'cms.published': {
    eventType: 'cms.published', label: 'Page Published', category: 'content', defaultSeverity: 'success',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'cms.unpublished': {
    eventType: 'cms.unpublished', label: 'Page Unpublished', category: 'content', defaultSeverity: 'warning',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'cms.rollback': {
    eventType: 'cms.rollback', label: 'Content Rolled Back', category: 'content', defaultSeverity: 'warning',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'cms.archived': {
    eventType: 'cms.archived', label: 'Content Archived', category: 'content', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'cms.navigation_updated': {
    eventType: 'cms.navigation_updated', label: 'Navigation Updated', category: 'content', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'cms.media_uploaded': {
    eventType: 'cms.media_uploaded', label: 'Media Uploaded', category: 'content', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'cms.redirect_created': {
    eventType: 'cms.redirect_created', label: 'Redirect Created', category: 'content', defaultSeverity: 'info',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'owner',
  },
  'cms.legal_published': {
    eventType: 'cms.legal_published', label: 'Legal Document Published', category: 'content', defaultSeverity: 'warning',
    requiresActivity: true, requiresAudit: true, dedupWindowMinutes: 0, externalDeliveryEligible: false,
    recipientRule: 'content_reviewer',
  },
  'cms.schedule_failed': {
    eventType: 'cms.schedule_failed', label: 'Scheduled Publish Failed', category: 'content', defaultSeverity: 'high',
    requiresActivity: true, requiresAudit: false, dedupWindowMinutes: 30, externalDeliveryEligible: true,
    recipientRule: 'owner',
  },
};

export function getEventDefinition(eventType: string): EventDefinition | undefined {
  return EVENT_CATALOGUE[eventType];
}

export const ACTIVITY_TYPE_LABELS: Record<string, string> = {
  'lead.created': 'Lead created',
  'lead.assigned': 'Lead assigned',
  'lead.converted': 'Lead converted to client',
  'client.created': 'Client account created',
  'client.archived': 'Client archived',
  'project.created': 'Project created',
  'project.status_changed': 'Project status updated',
  'project.at_risk': 'Project flagged at risk',
  'task.overdue': 'Task overdue',
  'milestone.completed': 'Milestone completed',
  'milestone.overdue': 'Milestone overdue',
  'invoice.issued': 'Invoice issued',
  'invoice.paid': 'Invoice paid',
  'invoice.overdue': 'Invoice overdue',
  'invoice.approval_requested': 'Invoice approval requested',
  'payment.recorded': 'Payment recorded',
  'incident.declared': 'Incident declared',
  'incident.resolved': 'Incident resolved',
  'automation.execution_failed': 'Workflow execution failed',
  'uat.feedback_submitted': 'UAT feedback submitted',
  'uat.critical_defect': 'Critical UAT defect reported',
  'uat.project_created': 'UAT project created',
  'uat.environment_ready': 'UAT environment ready',
  'uat.job_opened': 'UAT test job opened',
  'uat.application_submitted': 'Tester application submitted',
  'uat.application_decided': 'Tester application decided',
  'uat.assignment_offered': 'UAT assignment offered',
  'uat.assignment_accepted': 'UAT assignment accepted',
  'uat.session_submitted': 'UAT session submitted',
  'uat.feedback_triaged': 'UAT feedback triaged',
  'uat.clarification_requested': 'UAT clarification requested',
  'uat.resolution_recorded': 'UAT resolution recorded',
  'uat.retest_requested': 'UAT retest requested',
  'uat.retest_failed': 'UAT retest failed',
  'uat.retest_passed': 'UAT retest passed',
  'uat.approval_decided': 'UAT approval decided',
  'tester.payment_approved': 'Tester payment approved',
  'tester.payment_rejected': 'Tester payment rejected',
  'tester.payment_sent_to_finance': 'Tester payment sent to finance',
  'tester.payment_confirmed': 'Tester payment confirmed',
  'tester.payment_failed': 'Tester payment failed',
  'tester.dispute_opened': 'Tester payment dispute opened',
  'tester.dispute_resolved': 'Tester payment dispute resolved',
  'tester.onboarding_approved': 'Tester onboarding approved',
  'tester.status_changed': 'Tester status changed',
  'tester.warning_issued': 'Tester warning issued',
  'tester.restriction_applied': 'Tester restriction applied',
  'tester.rating_added': 'Tester rating added',
  'pbx.route_activated': 'PBX route activated',
  'pbx.service_failure': 'PBX service failure',
  'pbx.tenant_created': 'New PBX tenant created',
  'pbx.tenant_suspended': 'PBX tenant suspended',
  'pbx.number_assigned': 'PBX number assigned',
  'pbx.webhook_received': 'PBX webhook event received',
  'pbx.webhook_failed': 'PBX webhook processing failed',
  'pbx.sync_completed': 'PBX provider sync completed',
  'pbx.sync_failed': 'PBX provider sync failed',
  'pbx.cost_updated': 'PBX cost data updated',
  'content.published': 'Content published',
  'staff.permission_changed': 'Staff permissions changed',
  'staff.invited': 'Staff member invited',
  'staff.suspended': 'Staff member suspended',
  'staff.invitation_sent': 'Staff invitation sent',
  'staff.invitation_accepted': 'Staff invitation accepted',
  'staff.activated': 'Staff account activated',
  'staff.role_changed': 'Staff role changed',
  'staff.permission_set_changed': 'Permission set changed',
  'staff.temp_access_granted': 'Temporary access granted',
  'staff.temp_access_expired': 'Temporary access expired',
  'staff.access_requested': 'Access request submitted',
  'staff.access_approved': 'Access request approved',
  'staff.review_completed': 'Access review completed',
  'staff.delegation_created': 'Delegation created',
  'staff.offboarding_started': 'Staff offboarding started',
  'staff.offboarding_completed': 'Staff offboarding completed',
  'staff.service_account_rotated': 'Service account rotated',
  'deployment.failed': 'Deployment failed',
  'backup.failed': 'Backup failed',
  'submission.received': 'New submission received',
  'mention.created': 'You were mentioned',
  'lead.stage_changed': 'Lead stage changed',
  'lead.follow_up_due': 'Lead follow-up due',
  'lead.follow_up_overdue': 'Lead follow-up overdue',
  'workflow.activated': 'Workflow activated',
  'workflow.failed': 'Workflow execution failed',
  'workflow.retry_requested': 'Workflow retry requested',
  'workflow.disabled': 'Workflow disabled',
  'workflow.archived': 'Workflow archived',
  'webhook.failed': 'Webhook delivery failed',
  'webhook.activated': 'Webhook activated',
  'schedule.missed': 'Schedule missed',
  'schedule.activated': 'Schedule activated',
  'agent.approved': 'AI agent approved',
  'agent.activated': 'AI agent activated',
  'agent.failed': 'AI agent run failed',
  'agent.limit_warning': 'AI agent approaching limit',
  'agent.limit_reached': 'AI agent limit reached',
  'approval.pending': 'Automation approval pending',
  'approval.executed': 'Automation approval executed',
  'lockdown.activated': 'Emergency lockdown activated',
  'lead.merged': 'Leads merged',
  'lead.archived': 'Lead archived',
  'lead.note_added': 'Note added to lead',
  'client.status_changed': 'Client status changed',
  'client.contact_added': 'Client contact added',
  'client.service_activated': 'Client service activated',
  'client.portal_granted': 'Portal access granted',
  'client.onboarding_completed': 'Client onboarding completed',
  'client.offboarding_started': 'Client offboarding started',
  'client.note_added': 'Internal note added to client',
  'project.phase_updated': 'Project phase updated',
  'project.risk_identified': 'Project risk identified',
  'project.issue_logged': 'Project issue logged',
  'project.decision_made': 'Project decision made',
  'project.change_requested': 'Change request submitted',
  'project.change_approved': 'Change request approved',
  'project.file_uploaded': 'Project file uploaded',
  'project.team_changed': 'Project team changed',
  'project.launch_ready': 'Project ready for launch',
  'project.completed': 'Project completed',
  'project.archived': 'Project archived',
  'task.created': 'Task created',
  'task.status_changed': 'Task status updated',
  'task.assigned': 'Task assigned',
  'task.due_date_changed': 'Task due date changed',
  'task.dependency_added': 'Task dependency added',
  'task.comment_added': 'Comment added to task',
  'task.review_requested': 'Task review requested',
  'task.review_approved': 'Task review approved',
  'task.completed': 'Task completed',
  'task.cancelled': 'Task cancelled',
  'task.archived': 'Task archived',
  'task.recurrence_failed': 'Recurring task generation failed',
  'cms.revision_submitted': 'CMS revision submitted for review',
  'cms.revision_approved': 'CMS revision approved',
  'cms.published': 'Page published',
  'cms.unpublished': 'Page unpublished',
  'cms.rollback': 'Content rolled back to previous version',
  'cms.archived': 'Content archived',
  'cms.navigation_updated': 'Site navigation updated',
  'cms.media_uploaded': 'Media asset uploaded',
  'cms.redirect_created': 'URL redirect created',
  'cms.legal_published': 'Legal document published',
  'cms.schedule_failed': 'Scheduled publish failed',
};

export const ACTIVITY_ICONS: Record<string, string> = {
  'lead.created': 'ri-user-add-line',
  'lead.assigned': 'ri-user-received-line',
  'lead.converted': 'ri-user-star-line',
  'client.created': 'ri-building-line',
  'client.archived': 'ri-archive-line',
  'project.created': 'ri-folder-add-line',
  'project.status_changed': 'ri-edit-line',
  'project.at_risk': 'ri-error-warning-line',
  'task.overdue': 'ri-alert-line',
  'milestone.completed': 'ri-flag-line',
  'milestone.overdue': 'ri-timer-line',
  'invoice.issued': 'ri-bill-line',
  'invoice.paid': 'ri-money-pound-circle-line',
  'invoice.overdue': 'ri-error-warning-line',
  'invoice.approval_requested': 'ri-thumb-up-line',
  'payment.recorded': 'ri-bank-card-line',
  'incident.declared': 'ri-shield-flash-line',
  'incident.resolved': 'ri-shield-check-line',
  'automation.execution_failed': 'ri-robot-line',
  'uat.feedback_submitted': 'ri-feedback-line',
  'uat.critical_defect': 'ri-bug-line',
  'uat.project_created': 'ri-folder-add-line',
  'uat.environment_ready': 'ri-server-line',
  'uat.job_opened': 'ri-briefcase-line',
  'uat.application_submitted': 'ri-file-text-line',
  'uat.application_decided': 'ri-check-double-line',
  'uat.assignment_offered': 'ri-user-received-line',
  'uat.assignment_accepted': 'ri-user-follow-line',
  'uat.session_submitted': 'ri-play-circle-line',
  'uat.feedback_triaged': 'ri-filter-line',
  'uat.clarification_requested': 'ri-question-answer-line',
  'uat.resolution_recorded': 'ri-tools-line',
  'uat.retest_requested': 'ri-restart-line',
  'uat.retest_failed': 'ri-close-circle-line',
  'uat.retest_passed': 'ri-checkbox-circle-line',
  'uat.approval_decided': 'ri-shield-check-line',
  'tester.payment_approved': 'ri-hand-coin-line',
  'tester.payment_rejected': 'ri-close-circle-line',
  'tester.payment_sent_to_finance': 'ri-send-plane-line',
  'tester.payment_confirmed': 'ri-verified-badge-line',
  'tester.payment_failed': 'ri-error-warning-line',
  'tester.dispute_opened': 'ri-scales-line',
  'tester.dispute_resolved': 'ri-check-double-line',
  'cms.revision_submitted': 'ri-file-edit-line',
  'cms.revision_approved': 'ri-check-double-line',
  'cms.published': 'ri-upload-cloud-line',
  'cms.unpublished': 'ri-cloud-off-line',
  'cms.rollback': 'ri-arrow-go-back-line',
  'cms.archived': 'ri-archive-line',
  'cms.navigation_updated': 'ri-menu-line',
  'cms.media_uploaded': 'ri-image-add-line',
  'cms.redirect_created': 'ri-share-forward-line',
  'cms.legal_published': 'ri-scales-line',
  'cms.schedule_failed': 'ri-calendar-close-line',
  'tester.onboarding_approved': 'ri-user-star-line',
  'tester.status_changed': 'ri-arrow-left-right-line',
  'tester.warning_issued': 'ri-alert-line',
  'tester.restriction_applied': 'ri-shield-flash-line',
  'tester.rating_added': 'ri-star-line',
  'pbx.route_activated': 'ri-phone-line',
  'pbx.service_failure': 'ri-phone-find-line',
  'pbx.tenant_created': 'ri-building-line',
  'pbx.tenant_suspended': 'ri-building-line',
  'pbx.number_assigned': 'ri-phone-line',
  'pbx.webhook_received': 'ri-link',
  'pbx.webhook_failed': 'ri-link-unlink',
  'pbx.sync_completed': 'ri-refresh-line',
  'pbx.sync_failed': 'ri-refresh-line',
  'pbx.cost_updated': 'ri-money-pound-circle-line',
  'content.published': 'ri-file-text-line',
  'staff.permission_changed': 'ri-shield-keyhole-line',
  'staff.invited': 'ri-mail-send-line',
  'staff.suspended': 'ri-user-unfollow-line',
  'staff.invitation_sent': 'ri-mail-send-line',
  'staff.invitation_accepted': 'ri-user-star-line',
  'staff.activated': 'ri-user-follow-line',
  'staff.role_changed': 'ri-admin-line',
  'staff.permission_set_changed': 'ri-key-2-line',
  'staff.temp_access_granted': 'ri-timer-line',
  'staff.temp_access_expired': 'ri-timer-flash-line',
  'staff.access_requested': 'ri-file-list-3-line',
  'staff.access_approved': 'ri-check-double-line',
  'staff.review_completed': 'ri-file-search-line',
  'staff.delegation_created': 'ri-user-shared-line',
  'staff.offboarding_started': 'ri-logout-box-line',
  'staff.offboarding_completed': 'ri-archive-line',
  'staff.service_account_rotated': 'ri-refresh-line',
  'deployment.failed': 'ri-cloud-off-line',
  'backup.failed': 'ri-hard-drive-2-line',
  'submission.received': 'ri-mail-line',
  'mention.created': 'ri-at-line',
  'lead.stage_changed': 'ri-arrow-left-right-line',
  'lead.follow_up_due': 'ri-calendar-event-line',
  'lead.follow_up_overdue': 'ri-calendar-close-line',
  'lead.merged': 'ri-merge-cells-horizontal',
  'lead.archived': 'ri-archive-line',
  'lead.note_added': 'ri-sticky-note-line',
  'client.status_changed': 'ri-arrow-left-right-line',
  'client.contact_added': 'ri-user-add-line',
  'client.service_activated': 'ri-rocket-line',
  'client.portal_granted': 'ri-shield-user-line',
  'client.onboarding_completed': 'ri-check-double-line',
  'client.offboarding_started': 'ri-logout-box-line',
  'client.note_added': 'ri-sticky-note-line',
  'project.phase_updated': 'ri-stack-line',
  'project.risk_identified': 'ri-error-warning-line',
  'project.issue_logged': 'ri-bug-line',
  'project.decision_made': 'ri-scales-line',
  'project.change_requested': 'ri-git-branch-line',
  'project.change_approved': 'ri-check-double-line',
  'project.file_uploaded': 'ri-file-upload-line',
  'project.team_changed': 'ri-group-line',
  'project.launch_ready': 'ri-rocket-line',
  'project.completed': 'ri-check-double-line',
  'project.archived': 'ri-archive-line',
  'task.created': 'ri-task-line',
  'task.status_changed': 'ri-arrow-left-right-line',
  'task.assigned': 'ri-user-received-line',
  'task.due_date_changed': 'ri-calendar-event-line',
  'task.dependency_added': 'ri-git-branch-line',
  'task.comment_added': 'ri-chat-1-line',
  'task.review_requested': 'ri-eye-line',
  'task.review_approved': 'ri-check-double-line',
  'task.completed': 'ri-checkbox-circle-line',
  'task.cancelled': 'ri-close-circle-line',
  'task.archived': 'ri-archive-line',
  'task.recurrence_failed': 'ri-refresh-line',
  'workflow.activated': 'ri-play-circle-line',
  'workflow.failed': 'ri-close-circle-line',
  'workflow.retry_requested': 'ri-restart-line',
  'workflow.disabled': 'ri-pause-circle-line',
  'workflow.archived': 'ri-archive-line',
  'webhook.failed': 'ri-link-unlink',
  'webhook.activated': 'ri-link',
  'schedule.missed': 'ri-timer-flash-line',
  'schedule.activated': 'ri-timer-line',
  'agent.approved': 'ri-robot-line',
  'agent.activated': 'ri-robot-line',
  'agent.failed': 'ri-robot-line',
  'agent.limit_warning': 'ri-alert-line',
  'agent.limit_reached': 'ri-prohibited-line',
  'approval.pending': 'ri-hourglass-line',
  'approval.executed': 'ri-check-double-line',
  'lockdown.activated': 'ri-shield-flash-line',
};

export const ACTIVITY_COLORS: Record<string, string> = {
  'lead.created': '#06B6D4',
  'lead.assigned': '#8B5CF6',
  'lead.converted': '#10B981',
  'client.created': '#06B6D4',
  'client.archived': '#F59E0B',
  'project.created': '#06B6D4',
  'project.status_changed': '#3B82F6',
  'project.at_risk': '#EF4444',
  'task.overdue': '#EF4444',
  'milestone.completed': '#10B981',
  'milestone.overdue': '#F97316',
  'invoice.issued': '#06B6D4',
  'invoice.paid': '#10B981',
  'invoice.overdue': '#EF4444',
  'invoice.approval_requested': '#F59E0B',
  'payment.recorded': '#10B981',
  'incident.declared': '#EF4444',
  'incident.resolved': '#10B981',
  'automation.execution_failed': '#EF4444',
  'uat.feedback_submitted': '#06B6D4',
  'uat.critical_defect': '#EF4444',
  'uat.project_created': '#06B6D4',
  'uat.environment_ready': '#10B981',
  'uat.job_opened': '#06B6D4',
  'uat.application_submitted': '#06B6D4',
  'uat.application_decided': '#8B5CF6',
  'uat.assignment_offered': '#06B6D4',
  'uat.assignment_accepted': '#10B981',
  'uat.session_submitted': '#3B82F6',
  'uat.feedback_triaged': '#8B5CF6',
  'uat.clarification_requested': '#F59E0B',
  'uat.resolution_recorded': '#10B981',
  'uat.retest_requested': '#F97316',
  'uat.retest_failed': '#EF4444',
  'uat.retest_passed': '#10B981',
  'uat.approval_decided': '#8B5CF6',
  'tester.payment_approved': '#10B981',
  'tester.payment_rejected': '#F97316',
  'tester.payment_sent_to_finance': '#3B82F6',
  'tester.payment_confirmed': '#10B981',
  'tester.payment_failed': '#EF4444',
  'tester.dispute_opened': '#F59E0B',
  'tester.dispute_resolved': '#10B981',
  'cms.revision_submitted': '#06B6D4',
  'cms.revision_approved': '#10B981',
  'cms.published': '#10B981',
  'cms.unpublished': '#F97316',
  'cms.rollback': '#F59E0B',
  'cms.archived': '#94A3B8',
  'cms.navigation_updated': '#3B82F6',
  'cms.media_uploaded': '#06B6D4',
  'cms.redirect_created': '#F97316',
  'cms.legal_published': '#EF4444',
  'cms.schedule_failed': '#EF4444',
  'tester.onboarding_approved': '#10B981',
  'tester.status_changed': '#F97316',
  'tester.warning_issued': '#F59E0B',
  'tester.restriction_applied': '#DC2626',
  'tester.rating_added': '#06B6D4',
  'pbx.route_activated': '#06B6D4',
  'pbx.service_failure': '#EF4444',
  'pbx.tenant_created': '#06B6D4',
  'pbx.tenant_suspended': '#F97316',
  'pbx.number_assigned': '#10B981',
  'pbx.webhook_received': '#06B6D4',
  'pbx.webhook_failed': '#EF4444',
  'pbx.sync_completed': '#10B981',
  'pbx.sync_failed': '#EF4444',
  'pbx.cost_updated': '#06B6D4',
  'content.published': '#10B981',
  'staff.permission_changed': '#F59E0B',
  'staff.invited': '#06B6D4',
  'staff.suspended': '#EF4444',
  'staff.invitation_sent': '#3B82F6',
  'staff.invitation_accepted': '#10B981',
  'staff.activated': '#10B981',
  'staff.role_changed': '#F59E0B',
  'staff.permission_set_changed': '#8B5CF6',
  'staff.temp_access_granted': '#F97316',
  'staff.temp_access_expired': '#94A3B8',
  'staff.access_requested': '#3B82F6',
  'staff.access_approved': '#10B981',
  'staff.review_completed': '#06B6D4',
  'staff.delegation_created': '#8B5CF6',
  'staff.offboarding_started': '#F97316',
  'staff.offboarding_completed': '#94A3B8',
  'staff.service_account_rotated': '#F59E0B',
  'deployment.failed': '#EF4444',
  'backup.failed': '#F97316',
  'submission.received': '#06B6D4',
  'mention.created': '#8B5CF6',
  'lead.stage_changed': '#06B6D4',
  'lead.follow_up_due': '#F59E0B',
  'lead.follow_up_overdue': '#EF4444',
  'lead.merged': '#8B5CF6',
  'lead.archived': '#94A3B8',
  'lead.note_added': '#06B6D4',
  'client.status_changed': '#3B82F6',
  'client.contact_added': '#06B6D4',
  'client.service_activated': '#10B981',
  'client.portal_granted': '#8B5CF6',
  'client.onboarding_completed': '#10B981',
  'client.offboarding_started': '#F97316',
  'client.note_added': '#06B6D4',
  'project.phase_updated': '#3B82F6',
  'project.risk_identified': '#F97316',
  'project.issue_logged': '#EF4444',
  'project.decision_made': '#8B5CF6',
  'project.change_requested': '#F59E0B',
  'project.change_approved': '#10B981',
  'project.file_uploaded': '#06B6D4',
  'project.team_changed': '#8B5CF6',
  'project.launch_ready': '#10B981',
  'project.completed': '#10B981',
  'project.archived': '#94A3B8',
  'task.created': '#06B6D4',
  'task.status_changed': '#3B82F6',
  'task.assigned': '#8B5CF6',
  'task.due_date_changed': '#F59E0B',
  'task.dependency_added': '#06B6D4',
  'task.comment_added': '#14B8A6',
  'task.review_requested': '#8B5CF6',
  'task.review_approved': '#10B981',
  'task.completed': '#10B981',
  'task.cancelled': '#94A3B8',
  'task.archived': '#94A3B8',
  'task.recurrence_failed': '#EF4444',
  'workflow.activated': '#10B981',
  'workflow.failed': '#EF4444',
  'workflow.retry_requested': '#3B82F6',
  'workflow.disabled': '#F97316',
  'workflow.archived': '#94A3B8',
  'webhook.failed': '#EF4444',
  'webhook.activated': '#10B981',
  'schedule.missed': '#EF4444',
  'schedule.activated': '#10B981',
  'agent.approved': '#10B981',
  'agent.activated': '#10B981',
  'agent.failed': '#EF4444',
  'agent.limit_warning': '#F59E0B',
  'agent.limit_reached': '#EF4444',
  'approval.pending': '#F59E0B',
  'approval.executed': '#10B981',
  'lockdown.activated': '#DC2626',
};

