import type {
  Property, Tenancy, MaintenanceIssue, ComplianceItem,
  RentRecord, Document, ActivityEvent, AttentionItem, Insight,
} from './types';

export const initialProperties: Property[] = [
  {
    id: 'prop-1',
    address: '14 Oakfield Road',
    city: 'Manchester',
    status: 'Occupied',
    tenantName: 'Emma Clarke',
    rentAmount: 1250,
    rentFrequency: 'Monthly',
    nextPaymentDate: '1 Sep 2026',
    complianceStatus: 'Current',
    openRepairs: 1,
    healthScore: 82,
  },
  {
    id: 'prop-2',
    address: '8 Milton Avenue',
    city: 'Leeds',
    status: 'Occupied',
    tenantName: 'James Patel',
    rentAmount: 975,
    rentFrequency: 'Monthly',
    nextPaymentDate: '5 Sep 2026',
    complianceStatus: 'Expiring Soon',
    openRepairs: 0,
    healthScore: 74,
  },
  {
    id: 'prop-3',
    address: '22 Willow Close',
    city: 'Birmingham',
    status: 'Occupied',
    tenantName: 'Daniel Harper',
    rentAmount: 1250,
    rentFrequency: 'Monthly',
    nextPaymentDate: '10 Aug 2026',
    complianceStatus: 'Current',
    openRepairs: 0,
    healthScore: 68,
  },
  {
    id: 'prop-4',
    address: '4 Hawthorn Court',
    city: 'Nottingham',
    status: 'Vacant',
    tenantName: '',
    rentAmount: 850,
    rentFrequency: 'Monthly',
    nextPaymentDate: '-',
    complianceStatus: 'Current',
    openRepairs: 0,
    healthScore: 90,
  },
  {
    id: 'prop-5',
    address: '31 Riverbank Drive',
    city: 'Sheffield',
    status: 'Occupied',
    tenantName: 'Sophie Walsh',
    rentAmount: 1100,
    rentFrequency: 'Monthly',
    nextPaymentDate: '15 Sep 2026',
    complianceStatus: 'Current',
    openRepairs: 1,
    healthScore: 85,
  },
  {
    id: 'prop-6',
    address: '7 The Crescent',
    city: 'Leeds',
    status: 'Occupied',
    tenantName: 'Marcus Bennett',
    rentAmount: 1050,
    rentFrequency: 'Monthly',
    nextPaymentDate: '20 Sep 2026',
    complianceStatus: 'Current',
    openRepairs: 0,
    healthScore: 92,
  },
];

export const initialTenancies: Tenancy[] = [
  {
    id: 'ten-1',
    propertyId: 'prop-1',
    tenantName: 'Emma Clarke',
    tenantEmail: 'emma.clarke@example.com',
    tenantPhone: '07700 900123',
    startDate: '1 March 2026',
    endDate: '28 February 2027',
    rentAmount: 1250,
    depositAmount: 1442,
    depositStatus: 'Protected — Demo Status',
    nextReviewDate: '1 March 2027',
  },
  {
    id: 'ten-2',
    propertyId: 'prop-2',
    tenantName: 'James Patel',
    tenantEmail: 'james.patel@example.com',
    tenantPhone: '07700 900456',
    startDate: '15 June 2025',
    endDate: '14 June 2026',
    rentAmount: 975,
    depositAmount: 1125,
    depositStatus: 'Protected — Demo Status',
    nextReviewDate: '15 June 2026',
  },
  {
    id: 'ten-3',
    propertyId: 'prop-3',
    tenantName: 'Daniel Harper',
    tenantEmail: 'daniel.harper@example.com',
    tenantPhone: '07700 900789',
    startDate: '1 January 2026',
    endDate: '31 December 2026',
    rentAmount: 1250,
    depositAmount: 1442,
    depositStatus: 'Protected — Demo Status',
    nextReviewDate: '1 January 2027',
  },
  {
    id: 'ten-5',
    propertyId: 'prop-5',
    tenantName: 'Sophie Walsh',
    tenantEmail: 'sophie.walsh@example.com',
    tenantPhone: '07700 900321',
    startDate: '1 April 2026',
    endDate: '31 March 2027',
    rentAmount: 1100,
    depositAmount: 1269,
    depositStatus: 'Protected — Demo Status',
    nextReviewDate: '1 April 2027',
  },
  {
    id: 'ten-6',
    propertyId: 'prop-6',
    tenantName: 'Marcus Bennett',
    tenantEmail: 'marcus.bennett@example.com',
    tenantPhone: '07700 900654',
    startDate: '1 May 2026',
    endDate: '30 April 2027',
    rentAmount: 1050,
    depositAmount: 1211,
    depositStatus: 'Protected — Demo Status',
    nextReviewDate: '1 May 2027',
  },
];

export const initialMaintenance: MaintenanceIssue[] = [
  {
    id: 'rep-1',
    propertyId: 'prop-1',
    title: 'Boiler pressure dropping',
    description: 'Heating pressure keeps falling and needs repressurising every few days.',
    reportedBy: 'Emma Clarke',
    reportedAt: 'Today · 09:14',
    priority: 'High',
    status: 'New',
  },
  {
    id: 'rep-2',
    propertyId: 'prop-5',
    title: 'Kitchen tap dripping',
    description: 'Constant drip from kitchen mixer tap. Worsening over the past week.',
    reportedBy: 'Sophie Walsh',
    reportedAt: 'Yesterday · 16:30',
    priority: 'Medium',
    status: 'New',
  },
  {
    id: 'rep-3',
    propertyId: 'prop-4',
    title: 'Pre-let deep clean required',
    description: 'Property needs professional deep clean before next tenancy.',
    reportedBy: 'Property Manager',
    reportedAt: '3 days ago',
    priority: 'Low',
    status: 'New',
  },
];

export const initialCompliance: ComplianceItem[] = [
  { id: 'comp-1', propertyId: 'prop-1', type: 'Gas Safety', expiryDate: '15 March 2027', status: 'Current' },
  { id: 'comp-2', propertyId: 'prop-2', type: 'Gas Safety', expiryDate: '22 Aug 2026', status: 'Expiring Soon' },
  { id: 'comp-3', propertyId: 'prop-2', type: 'Electrical Safety', expiryDate: '10 Nov 2026', status: 'Current' },
  { id: 'comp-4', propertyId: 'prop-3', type: 'Gas Safety', expiryDate: '5 Jan 2027', status: 'Current' },
  { id: 'comp-5', propertyId: 'prop-1', type: 'EPC', expiryDate: '20 June 2027', status: 'Current' },
  { id: 'comp-6', propertyId: 'prop-3', type: 'Smoke/CO Alarms', expiryDate: '15 Dec 2026', status: 'Current' },
  { id: 'comp-7', propertyId: 'prop-5', type: 'Gas Safety', expiryDate: '1 Oct 2026', status: 'Current' },
  { id: 'comp-8', propertyId: 'prop-6', type: 'Right to Rent', expiryDate: '30 Apr 2027', status: 'Current' },
  { id: 'comp-9', propertyId: 'prop-1', type: 'Deposit', expiryDate: '28 Feb 2027', status: 'Current' },
  { id: 'comp-10', propertyId: 'prop-2', type: 'Property Licensing', expiryDate: '30 Jun 2027', status: 'Current' },
];

export const initialRent: RentRecord[] = [
  { id: 'rent-1', propertyId: 'prop-1', tenantName: 'Emma Clarke', amount: 1250, dueDate: '1 Aug 2026', status: 'Paid', paidDate: '1 Aug 2026' },
  { id: 'rent-2', propertyId: 'prop-2', tenantName: 'James Patel', amount: 975, dueDate: '5 Aug 2026', status: 'Paid', paidDate: '4 Aug 2026' },
  { id: 'rent-3', propertyId: 'prop-3', tenantName: 'Daniel Harper', amount: 1250, dueDate: '10 Aug 2026', status: 'Outstanding' },
  { id: 'rent-5', propertyId: 'prop-5', tenantName: 'Sophie Walsh', amount: 1100, dueDate: '15 Aug 2026', status: 'Paid', paidDate: '14 Aug 2026' },
  { id: 'rent-6', propertyId: 'prop-6', tenantName: 'Marcus Bennett', amount: 1050, dueDate: '20 Aug 2026', status: 'Paid', paidDate: '18 Aug 2026' },
];

export const initialDocuments: Document[] = [
  { id: 'doc-1', propertyId: 'prop-1', category: 'Tenancy', title: 'Tenancy Agreement — Emma Clarke', date: '28 Feb 2026' },
  { id: 'doc-2', propertyId: 'prop-1', category: 'Compliance', title: 'Gas Safety Certificate', date: '15 Mar 2026' },
  { id: 'doc-3', propertyId: 'prop-1', category: 'Compliance', title: 'EPC Report', date: '20 Jun 2024' },
  { id: 'doc-4', propertyId: 'prop-2', category: 'Tenancy', title: 'Tenancy Agreement — James Patel', date: '14 Jun 2025' },
  { id: 'doc-5', propertyId: 'prop-2', category: 'Compliance', title: 'Electrical Safety Certificate', date: '10 Nov 2024' },
  { id: 'doc-6', propertyId: 'prop-3', category: 'Tenancy', title: 'Tenancy Agreement — Daniel Harper', date: '31 Dec 2025' },
  { id: 'doc-7', propertyId: 'prop-3', category: 'Finance', title: 'Inventory Report', date: '1 Jan 2026' },
  { id: 'doc-8', propertyId: 'prop-5', category: 'Tenancy', title: 'Tenancy Agreement — Sophie Walsh', date: '31 Mar 2026' },
  { id: 'doc-9', propertyId: 'prop-6', category: 'Tenancy', title: 'Tenancy Agreement — Marcus Bennett', date: '30 Apr 2026' },
  { id: 'doc-10', propertyId: 'prop-1', category: 'Finance', title: 'Rent Statement — Aug 2026', date: '1 Aug 2026' },
];

export const initialActivity: ActivityEvent[] = [
  { id: 'act-1', time: '14:42', title: 'Tenant message received', detail: 'Emma Clarke — 14 Oakfield Road', property: '14 Oakfield Road', type: 'message' },
  { id: 'act-2', time: '14:18', title: 'Gas safety reminder created', detail: '8 Milton Avenue — expires 22 Aug', property: '8 Milton Avenue', type: 'compliance' },
  { id: 'act-3', time: '13:46', title: 'Rent payment recorded', detail: 'Sophie Walsh — £1,100', property: '31 Riverbank Drive', type: 'rent' },
  { id: 'act-4', time: '12:03', title: 'Maintenance reported', detail: 'Boiler pressure — 14 Oakfield Road', property: '14 Oakfield Road', type: 'maintenance' },
  { id: 'act-5', time: '11:28', title: 'Tenancy review scheduled', detail: 'James Patel — 8 Milton Avenue', property: '8 Milton Avenue', type: 'general' },
  { id: 'act-6', time: '09:14', title: 'Tenant reported issue', detail: 'Boiler pressure dropping', property: '14 Oakfield Road', type: 'maintenance' },
];

export const initialAttention: AttentionItem[] = [
  {
    id: 'att-1',
    type: 'maintenance',
    property: '14 Oakfield Road',
    title: 'Boiler pressure issue reported',
    detail: 'High priority repair awaiting action',
    priority: 'High',
    propertyId: 'prop-1',
  },
  {
    id: 'att-2',
    type: 'compliance',
    property: '8 Milton Avenue',
    title: 'Gas safety certificate expires soon',
    detail: 'Expires in 12 days',
    priority: 'Medium',
    propertyId: 'prop-2',
  },
  {
    id: 'att-3',
    type: 'rent',
    property: '22 Willow Close',
    title: 'Rent payment overdue',
    detail: 'Expected yesterday · £1,250',
    priority: 'Medium',
    propertyId: 'prop-3',
  },
];

export const initialInsights: Insight[] = [
  {
    id: 'ins-1',
    category: 'maintenance',
    title: 'Boiler issue requires action',
    detail: 'Recommendation: Assign heating engineer.',
    status: 'active',
    actionText: 'Review Repair',
  },
  {
    id: 'ins-2',
    category: 'compliance',
    title: 'Gas safety expires in 12 days',
    detail: 'Recommendation: Arrange renewal.',
    status: 'active',
    actionText: 'Review Compliance',
  },
  {
    id: 'ins-3',
    category: 'rent',
    title: 'One payment is overdue',
    detail: 'Recommendation: Review tenant account.',
    status: 'active',
    actionText: 'Review Rent',
  },
];

export const demoContractors = [
  { name: 'Northwest Heating Ltd', type: 'Heating Engineer', availability: 'Available tomorrow' },
  { name: 'Oak & Stone Maintenance', type: 'General Maintenance', availability: 'Available Friday' },
  { name: 'RapidHeat Services', type: 'Heating Engineer', availability: 'Available today' },
];

export const navItems = [
  { key: 'overview', label: 'Overview', icon: 'ri-dashboard-line' },
  { key: 'properties', label: 'Properties', icon: 'ri-home-4-line' },
  { key: 'tenancies', label: 'Tenancies', icon: 'ri-user-line' },
  { key: 'maintenance', label: 'Maintenance', icon: 'ri-tools-line' },
  { key: 'compliance', label: 'Compliance', icon: 'ri-shield-check-line' },
  { key: 'rent', label: 'Rent', icon: 'ri-wallet-line' },
  { key: 'documents', label: 'Documents', icon: 'ri-file-list-line' },
  { key: 'messages', label: 'Messages', icon: 'ri-message-2-line' },
];