import type { ProductConfig } from './types'

export const productConfigs: Record<string, ProductConfig> = {
  'business-command-centre': {
    id: 'business-command-centre',
    name: 'Northstar Business OS',
    shortName: 'Command Centre',
    workspaceOrg: 'Digital Footprint (demo)',
    accent: 'cyan',
    statusLabel: 'INTERACTIVE DEMO',
    statusDescription: 'Uses fictional demo data. No production customer information is shown.',
    ctaText: 'Build This For My Business',
    completionHeading: "You've run the business.",
    completionAccomplishments: [
      'Reviewed business health and performance metrics',
      'Checked active projects and delivery status',
      'Assessed team capacity and workload',
      'Reviewed financial position and forecasts',
      'Resolved an attention item',
      'Took action on operational insights',
    ],
    completionOutcome: 'Now imagine this running your company — every day, every decision, visible and supported.',
    completionCtaText: 'Build My Command Centre',
    enquiryHeading: 'Imagine this with your business inside it.',
    enquiryImagination: 'Imagine this running your company.',
    enquiryModules: [
      'Operations dashboard',
      'Project management',
      'Staff management',
      'Finance visibility',
      'CRM & sales',
      'Automation',
      'Customer portal',
      'Something bespoke',
    ],
    enquirySource: 'business-command-centre-demo',
    demoNoticeExtras: [],
    tourSteps: [
      { view: 'overview', title: 'Your Business At A Glance', instruction: 'See the headline metrics that tell you how the business is performing today.' },
      { view: 'attention', title: 'What Needs Your Attention', instruction: 'Spot what needs action before it becomes a problem.' },
      { view: 'projects', title: 'Active Projects', instruction: 'Track every project, every milestone and every deadline.' },
      { view: 'people', title: 'Team Capacity', instruction: 'See who is at capacity and who can take more work.' },
      { view: 'tasks', title: "Today's Work", instruction: 'Know what is due, what is late and what is complete.' },
      { view: 'finance', title: 'Financial Position', instruction: 'Understand revenue, costs and cash without opening a spreadsheet.' },
    ],
    bgBase: 'bg-[#060a14]',
    bgHeader: 'bg-[#0a0f1a]',
    borderColor: 'border-white/[0.05]',
    textPrimary: 'text-white',
    textSecondary: 'text-slate-300',
    textMuted: 'text-slate-500',
    accentText: 'text-cyan-400',
    accentBg: 'bg-cyan-500/15',
    accentBorder: 'border-cyan-500/20',
    ctaBg: 'bg-white/[0.08]',
    ctaHoverBg: 'hover:bg-white/[0.14]',
    ctaTextColor: 'text-white',
    buttonHoverBg: 'hover:bg-white/[0.05]',
    iconColor: 'text-cyan-400',
  },
  'ai-lead-system': {
    id: 'ai-lead-system',
    name: 'Northstar AI Sales Engine',
    shortName: 'AI Sales',
    workspaceOrg: 'Northstar Co.',
    accent: 'orange',
    statusLabel: 'INTERACTIVE DEMO',
    statusDescription: 'Uses fictional demo data. No external business is researched or contacted.',
    ctaText: 'Build My Sales System',
    completionHeading: "You've turned an enquiry into an opportunity.",
    completionAccomplishments: [
      'Reviewed an incoming web enquiry',
      'Explored AI research and qualification',
      'Understood the lead scoring methodology',
      'Reviewed AI-generated response suggestions',
      'Moved the lead through the pipeline',
    ],
    completionOutcome: 'AI qualification, research and responses — with a human making every decision.',
    completionCtaText: 'Build My AI Sales System',
    enquiryHeading: 'Imagine your sales team supported by AI intelligence.',
    enquiryImagination: 'Imagine your sales pipeline with AI-assisted research and qualification.',
    enquiryModules: [
      'AI lead research',
      'Qualification scoring',
      'Response generation',
      'Pipeline management',
      'CRM integration',
      'Email automation',
      'Meeting scheduling',
      'Something bespoke',
    ],
    enquirySource: 'ai-lead-system-demo',
    demoNoticeExtras: ['No external business is researched or contacted'],
    tourSteps: [
      { view: 'queue', title: 'The Lead Queue', instruction: 'See incoming enquiries waiting for qualification.' },
      { view: 'workspace', title: 'AI Research & Qualification', instruction: 'Explore how AI researches and scores a lead.' },
      { view: 'workspace', title: 'Response Generation', instruction: 'Review AI-generated responses before sending.' },
      { view: 'workspace', title: 'Pipeline Management', instruction: 'Move qualified leads through your sales pipeline.' },
    ],
    bgBase: 'bg-[#060a14]',
    bgHeader: 'bg-[#0b0f19]/95',
    borderColor: 'border-white/[0.07]',
    textPrimary: 'text-white',
    textSecondary: 'text-slate-300',
    textMuted: 'text-slate-500',
    accentText: 'text-orange-400',
    accentBg: 'bg-orange-500/15',
    accentBorder: 'border-orange-500/20',
    ctaBg: 'bg-white/[0.08]',
    ctaHoverBg: 'hover:bg-white/[0.14]',
    ctaTextColor: 'text-white',
    buttonHoverBg: 'hover:bg-white/[0.05]',
    iconColor: 'text-orange-400',
  },
  'customer-portal': {
    id: 'customer-portal',
    name: 'Customer Portal',
    shortName: 'Customer Portal',
    workspaceOrg: 'Aster & Co.',
    accent: 'violet',
    statusLabel: 'INTERACTIVE DEMO',
    statusDescription: 'Uses fictional demo data. No payment or project communication is sent externally.',
    ctaText: 'Build My Client Portal',
    completionHeading: "You've experienced the project as the customer.",
    completionAccomplishments: [
      'Checked project progress and health',
      'Reviewed the project journey and milestones',
      'Approved the dashboard design',
      'Sent a project message',
      'Accessed project files and documents',
      'Understood the payment position',
    ],
    completionOutcome: 'Now imagine every customer receiving this level of clarity.',
    completionCtaText: 'Build My Customer Portal',
    enquiryHeading: 'Imagine your customers using this.',
    enquiryImagination: 'Imagine your customers tracking their projects from one calm, professional place.',
    enquiryModules: [
      'Track projects',
      'Approve work',
      'Send messages',
      'Access files',
      'View invoices',
      'Make payments',
      'Book appointments',
      'Manage services',
      'Something bespoke',
    ],
    enquirySource: 'customer-portal-demo',
    demoNoticeExtras: ['No payment or project communication is sent externally'],
    tourSteps: [
      { view: 'overview', title: 'Project Overview', instruction: 'See the project at a glance — phase, completion and next milestone.' },
      { view: 'milestones', title: 'Project Journey', instruction: 'Follow every milestone from discovery through to launch.' },
      { view: 'approvals', title: 'Approve Work', instruction: 'Review submissions and approve completed work.' },
      { view: 'messages', title: 'Messages', instruction: 'Stay in touch without digging through email threads.' },
      { view: 'files', title: 'Files & Documents', instruction: 'Find everything in one organised library.' },
      { view: 'billing', title: 'Payment Position', instruction: 'See invoices and understand where payments stand.' },
    ],
    bgBase: 'bg-white',
    bgHeader: 'bg-white/90',
    borderColor: 'border-[#e8e5df]',
    textPrimary: 'text-[#1a2332]',
    textSecondary: 'text-[#6b7b8e]',
    textMuted: 'text-[#8a8a8a]',
    accentText: 'text-[#3b82f6]',
    accentBg: 'bg-[#3b82f6]/10',
    accentBorder: 'border-[#3b82f6]/20',
    ctaBg: 'bg-[#1a2332]',
    ctaHoverBg: 'hover:bg-[#2a3342]',
    ctaTextColor: 'text-white',
    buttonHoverBg: 'hover:bg-[#f6f5f2]',
    iconColor: 'text-[#f97316]',
  },
  'quickguard-walkthrough': {
    id: 'quickguard-walkthrough',
    name: 'QuickGuard',
    shortName: 'QuickGuard',
    workspaceOrg: 'Marketplace Experience',
    accent: 'emerald',
    statusLabel: 'GUIDED EXPERIENCE',
    statusDescription: 'Uses fictional demo data. No booking or payment is created.',
    ctaText: 'Build a Marketplace Like This',
    completionHeading: "You've run both sides of the marketplace.",
    completionAccomplishments: [
      'Created a security job',
      'Matched suitable guards',
      'Accepted work as a guard',
      'Confirmed the security team',
      'Checked into the shift',
      'Logged activity',
      'Completed the work',
      'Approved payment',
      'Closed the job',
    ],
    completionOutcome: 'One platform. Two sides. One complete marketplace.',
    completionCtaText: 'Build My Marketplace',
    enquiryHeading: 'Want a marketplace like this?',
    enquiryImagination: 'Imagine your industry running on a two-sided platform.',
    enquiryModules: [
      'Job creation & matching',
      'Worker profiles',
      'Booking lifecycle',
      'Payment flow',
      'Ratings & reviews',
      'Mobile app',
      'Client dashboard',
      'Something bespoke',
    ],
    enquirySource: 'quickguard-demo',
    demoNoticeExtras: ['No booking or payment is created'],
    tourSteps: [
      { title: 'Create a Security Job', instruction: 'Set up a security booking with location, date and requirements.' },
      { title: 'Match Guards', instruction: 'See how the system matches available guards to the job.' },
      { title: 'Confirm the Team', instruction: 'Select and confirm your security team.' },
      { title: 'Guard Perspective', instruction: 'Switch to the guard view and accept the job.' },
      { title: 'Check In & Work', instruction: 'Check into the shift and log activity.' },
      { title: 'Complete & Pay', instruction: 'Finish the job, approve payment and close.' },
    ],
    bgBase: 'bg-[#060a14]',
    bgHeader: 'bg-[#080c14]/95',
    borderColor: 'border-white/[0.06]',
    textPrimary: 'text-white',
    textSecondary: 'text-slate-300',
    textMuted: 'text-slate-500',
    accentText: 'text-blue-400',
    accentBg: 'bg-blue-500/15',
    accentBorder: 'border-blue-500/20',
    ctaBg: 'bg-white/[0.08]',
    ctaHoverBg: 'hover:bg-white/[0.14]',
    ctaTextColor: 'text-white',
    buttonHoverBg: 'hover:bg-white/[0.05]',
    iconColor: 'text-blue-400',
  },
  'guardianhub-preview': {
    id: 'guardianhub-preview',
    name: 'GuardianHub',
    shortName: 'GuardianHub',
    workspaceOrg: 'Atlas Security Group (demo)',
    accent: 'cyan',
    statusLabel: 'PRODUCT PREVIEW',
    statusDescription: 'Uses fictional demo data. No people are being tracked.',
    ctaText: 'Build My Security Platform',
    completionHeading: "You've run the control room.",
    completionAccomplishments: [
      'Monitored active sites and guard deployment',
      'Completed patrol checkpoints',
      'Resolved an active incident',
      'Assigned guards to the rota',
      'Reviewed compliance records',
      'Checked client-facing reports',
    ],
    completionOutcome: 'Security operations visible, accountable and running from one place.',
    completionCtaText: 'Build My Security Platform',
    enquiryHeading: 'Imagine your security operation inside this.',
    enquiryImagination: 'Imagine your security operations visible, accountable and running from one place.',
    enquiryModules: [
      'Site management',
      'Guard deployment',
      'Incident logging',
      'Patrol tracking',
      'Compliance records',
      'Client reporting',
      'Rota management',
      'Something bespoke',
    ],
    enquirySource: 'guardianhub-demo',
    demoNoticeExtras: ['No people are being tracked'],
    tourSteps: [
      { view: 'command', title: 'Command Centre', instruction: 'See all sites, guards and incidents at a glance.' },
      { view: 'patrols', title: 'Patrol Tracking', instruction: 'Follow patrol progress and complete checkpoints.' },
      { view: 'incidents', title: 'Incident Management', instruction: 'Track and resolve incidents from detection to closure.' },
      { view: 'rota', title: 'Rota Management', instruction: 'Assign guards and balance shift coverage.' },
      { view: 'compliance', title: 'Compliance', instruction: 'Keep certification and compliance records current.' },
    ],
    bgBase: 'bg-[#060a14]',
    bgHeader: 'bg-[#0a0f19]',
    borderColor: 'border-white/[0.04]',
    textPrimary: 'text-white',
    textSecondary: 'text-slate-300',
    textMuted: 'text-slate-500',
    accentText: 'text-cyan-400',
    accentBg: 'bg-cyan-500/15',
    accentBorder: 'border-cyan-500/20',
    ctaBg: 'bg-white/[0.08]',
    ctaHoverBg: 'hover:bg-white/[0.14]',
    ctaTextColor: 'text-white',
    buttonHoverBg: 'hover:bg-white/[0.05]',
    iconColor: 'text-cyan-400',
  },
  'lethub-lettings-tour': {
    id: 'lethub-lettings-tour',
    name: 'LetHub',
    shortName: 'LetHub',
    workspaceOrg: 'LetHub Portfolio (demo)',
    accent: 'amber',
    statusLabel: 'PRODUCT PREVIEW',
    statusDescription: 'Uses fictional demo data. No payment, tenancy or legal record is created.',
    ctaText: 'Build My Property Platform',
    completionHeading: "You've managed the portfolio.",
    completionAccomplishments: [
      'Reviewed property portfolio health',
      'Assigned a contractor to a repair',
      'Renewed a compliance certificate',
      'Recorded a rent payment',
      'Viewed the tenant perspective',
      'Resolved attention items',
    ],
    completionOutcome: 'One connected platform for properties, tenants and maintenance.',
    completionCtaText: 'Build My Property Platform',
    enquiryHeading: 'Imagine your property portfolio managed from here.',
    enquiryImagination: 'Imagine your entire portfolio — properties, tenants, maintenance and compliance — in one place.',
    enquiryModules: [
      'Property management',
      'Tenant applications',
      'Maintenance tracking',
      'Rent management',
      'Compliance records',
      'Document storage',
      'Tenant portal',
      'Something bespoke',
    ],
    enquirySource: 'lethub-demo',
    demoNoticeExtras: ['No payment, tenancy or legal record is created'],
    tourSteps: [
      { view: 'overview', title: 'Portfolio Overview', instruction: 'See your entire portfolio health at a glance.' },
      { view: 'maintenance', title: 'Repairs & Maintenance', instruction: 'Assign contractors and track repairs to completion.' },
      { view: 'overview', title: 'Tenant Perspective', instruction: 'Switch to see what your tenants experience.' },
      { view: 'maintenance', title: 'Complete the Repair', instruction: 'Mark the repair as resolved for the tenant.' },
      { view: 'compliance', title: 'Compliance', instruction: 'Keep gas safety and other certificates current.' },
      { view: 'rent', title: 'Rent Management', instruction: 'Track payments and chase outstanding rent.' },
      { view: 'overview', title: 'Everything Connected', instruction: 'Your portfolio running from one platform.' },
    ],
    bgBase: 'bg-[#f7f5f2]',
    bgHeader: 'bg-[#f7f5f2]/95',
    borderColor: 'border-[#e8e5df]',
    textPrimary: 'text-[#1a2332]',
    textSecondary: 'text-[#6b7b8e]',
    textMuted: 'text-[#8a8a8a]',
    accentText: 'text-amber-600',
    accentBg: 'bg-amber-500/15',
    accentBorder: 'border-amber-500/20',
    ctaBg: 'bg-[#1a2332]',
    ctaHoverBg: 'hover:bg-[#2a3342]',
    ctaTextColor: 'text-white',
    buttonHoverBg: 'hover:bg-[#f0ede8]',
    iconColor: 'text-amber-500',
  },
  'synqoro-event-demo': {
    id: 'synqoro-event-demo',
    name: 'Synqoro',
    shortName: 'Synqoro',
    workspaceOrg: 'Synqoro Events (demo)',
    accent: 'rose',
    statusLabel: 'PRODUCT PREVIEW',
    statusDescription: 'Uses fictional demo data. No messages or supplier bookings are sent.',
    ctaText: 'Build My Event Platform',
    completionHeading: "You've run the event.",
    completionAccomplishments: [
      'Reviewed event planning dashboard',
      'Checked guest list and RSVPs',
      'Coordinated supplier bookings',
      'Managed the event schedule',
      'Monitored the live event view',
      'Reviewed post-event summary',
    ],
    completionOutcome: 'One platform for planning, coordination and live event operations.',
    completionCtaText: 'Build My Event Platform',
    enquiryHeading: 'Imagine your events running from here.',
    enquiryImagination: 'Imagine your events — planning, suppliers, guests and live operations — on one platform.',
    enquiryModules: [
      'Venue management',
      'Guest coordination',
      'Schedule planning',
      'Supplier tracking',
      'Live event operations',
      'Post-event reporting',
      'Budget management',
      'Something bespoke',
    ],
    enquirySource: 'synqoro-demo',
    demoNoticeExtras: ['No messages or supplier bookings are sent'],
    tourSteps: [
      { view: 'overview', title: 'Event Dashboard', instruction: 'See the full event picture — guests, suppliers and schedule.' },
      { view: 'guests', title: 'Guest Management', instruction: 'Track RSVPs, dietary requirements and seating.' },
      { view: 'suppliers', title: 'Supplier Coordination', instruction: 'Manage vendor bookings and communications.' },
      { view: 'schedule', title: 'Event Schedule', instruction: 'Follow the timeline from setup through to close.' },
      { view: 'live', title: 'Live Operations', instruction: 'Monitor the event as it happens.' },
    ],
    bgBase: 'bg-[#0a0a14]',
    bgHeader: 'bg-[#0c0c18]/95',
    borderColor: 'border-white/[0.06]',
    textPrimary: 'text-white',
    textSecondary: 'text-slate-300',
    textMuted: 'text-slate-500',
    accentText: 'text-rose-400',
    accentBg: 'bg-rose-500/15',
    accentBorder: 'border-rose-500/20',
    ctaBg: 'bg-white/[0.08]',
    ctaHoverBg: 'hover:bg-white/[0.14]',
    ctaTextColor: 'text-white',
    buttonHoverBg: 'hover:bg-white/[0.05]',
    iconColor: 'text-rose-400',
  },
}